In [1]:
import torch
from helpers import model_summary
x_dummy = torch.randn(5, 2)

## SIREN and FINER MODEL

In [2]:
from models.implicit_neural_representations.inr_models.siren_model import SirenModel, FinerModel

In [3]:
# initialize siren model without residual layers
siren_model = SirenModel(
    in_features=2,
    out_features=2,
    hidden_layers=5,
    hidden_features=512,
    first_omega_0=30.0,
    hidden_omega_0=30.0,
    residual_net=False
)

In [4]:
output = siren_model(x_dummy)

In [5]:
# Print input and output
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 0.2643,  0.4806],
        [-0.3880, -0.1166],
        [ 0.5267,  0.3416],
        [ 1.0770, -0.5350],
        [-0.4397,  0.7759]])
Output:
tensor([[-0.0388, -0.0204],
        [-0.0522, -0.0457],
        [-0.0048, -0.0228],
        [-0.0464, -0.0217],
        [-0.0655, -0.0056]], grad_fn=<MmBackward0>)


In [6]:
model_summary(siren_model, input_size=(1, 2))

Layer (type:depth-idx)                   Output Shape              Param #
SirenModel                               [1, 2]                    --
├─Sequential: 1-1                        [1, 2]                    --
│    └─SirenLayer: 2-1                   [1, 512]                  --
│    │    └─Linear: 3-1                  [1, 512]                  1,536
│    │    └─siren_activation: 3-2        [1, 512]                  --
│    └─SirenLayer: 2-2                   [1, 512]                  --
│    │    └─Linear: 3-3                  [1, 512]                  262,656
│    │    └─siren_activation: 3-4        [1, 512]                  --
│    └─SirenLayer: 2-3                   [1, 512]                  --
│    │    └─Linear: 3-5                  [1, 512]                  262,656
│    │    └─siren_activation: 3-6        [1, 512]                  --
│    └─SirenLayer: 2-4                   [1, 512]                  --
│    │    └─Linear: 3-7                  [1, 512]                  262,6

In [7]:
finer_model = FinerModel(
    in_features=2,
    out_features=2,
    bias=True,
    hidden_layers=5,
    hidden_features=128,
    first_omega_0=30.,
    hidden_omega_0=30.,
    first_k=10,
    hidden_k=10,
    residual_net=False
)

In [8]:
output = finer_model(x_dummy)

In [9]:
# Print input and output
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 0.2643,  0.4806],
        [-0.3880, -0.1166],
        [ 0.5267,  0.3416],
        [ 1.0770, -0.5350],
        [-0.4397,  0.7759]])
Output:
tensor([[ 0.0229,  0.0031],
        [-0.0652,  0.0059],
        [-0.0152, -0.0195],
        [-0.0025, -0.0124],
        [-0.0222,  0.0101]], grad_fn=<MmBackward0>)


In [10]:
model_summary(finer_model, input_size=(1, 2))

Layer (type:depth-idx)                   Output Shape              Param #
FinerModel                               [1, 2]                    --
├─Sequential: 1-1                        [1, 2]                    --
│    └─FinerLayer: 2-1                   [1, 128]                  --
│    │    └─Linear: 3-1                  [1, 128]                  384
│    │    └─siren_activation: 3-2        [1, 128]                  --
│    └─FinerLayer: 2-2                   [1, 128]                  --
│    │    └─Linear: 3-3                  [1, 128]                  16,512
│    │    └─siren_activation: 3-4        [1, 128]                  --
│    └─FinerLayer: 2-3                   [1, 128]                  --
│    │    └─Linear: 3-5                  [1, 128]                  16,512
│    │    └─siren_activation: 3-6        [1, 128]                  --
│    └─FinerLayer: 2-4                   [1, 128]                  --
│    │    └─Linear: 3-7                  [1, 128]                  16,512
│ 

In [11]:
siren_residual_model = SirenModel(
    in_features=2,
    out_features=2,
    hidden_layers=5,
    hidden_features=512,
    first_omega_0=30.0,
    hidden_omega_0=30.0,
    residual_net=True
)

In [12]:
output = siren_residual_model(x_dummy)

In [13]:
# Print input and output
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 0.2643,  0.4806],
        [-0.3880, -0.1166],
        [ 0.5267,  0.3416],
        [ 1.0770, -0.5350],
        [-0.4397,  0.7759]])
Output:
tensor([[ 0.0277, -0.0366],
        [ 0.0074, -0.0270],
        [-0.0413,  0.0171],
        [ 0.0061,  0.0266],
        [ 0.0329, -0.0358]], grad_fn=<MmBackward0>)


In [14]:
model_summary(siren_residual_model, input_size=(1, 2))

Layer (type:depth-idx)                   Output Shape              Param #
SirenModel                               [1, 2]                    --
├─Sequential: 1-1                        [1, 2]                    --
│    └─SirenLayer: 2-1                   [1, 512]                  --
│    │    └─Linear: 3-1                  [1, 512]                  1,536
│    │    └─siren_activation: 3-2        [1, 512]                  --
│    └─SirenResidualLayer: 2-2           [1, 512]                  --
│    │    └─Linear: 3-3                  [1, 512]                  262,656
│    │    └─siren_activation: 3-4        [1, 512]                  --
│    │    └─Linear: 3-5                  [1, 512]                  262,656
│    │    └─siren_activation: 3-6        [1, 512]                  --
│    └─SirenResidualLayer: 2-3           [1, 512]                  --
│    │    └─Linear: 3-7                  [1, 512]                  262,656
│    │    └─siren_activation: 3-8        [1, 512]                  

In [15]:
finer_residual_model = FinerModel( 
    in_features=2,
    out_features=2,
    bias=True,
    hidden_layers=5,
    hidden_features=128,
    first_omega_0=30.,
    hidden_omega_0=30.,
    first_k=10,
    hidden_k=10,
    residual_net=True
)

In [16]:
output = finer_residual_model(x_dummy)

In [17]:
# Print input and output
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 0.2643,  0.4806],
        [-0.3880, -0.1166],
        [ 0.5267,  0.3416],
        [ 1.0770, -0.5350],
        [-0.4397,  0.7759]])
Output:
tensor([[-0.0035,  0.0341],
        [-0.0207,  0.0164],
        [ 0.0116,  0.0411],
        [-0.0249, -0.0210],
        [-0.0307,  0.0480]], grad_fn=<MmBackward0>)


In [18]:
model_summary(finer_residual_model, input_size=(1, 2))

Layer (type:depth-idx)                   Output Shape              Param #
FinerModel                               [1, 2]                    --
├─Sequential: 1-1                        [1, 2]                    --
│    └─FinerLayer: 2-1                   [1, 128]                  --
│    │    └─Linear: 3-1                  [1, 128]                  384
│    │    └─siren_activation: 3-2        [1, 128]                  --
│    └─FinerResidualLayer: 2-2           [1, 128]                  --
│    │    └─Linear: 3-3                  [1, 128]                  16,512
│    │    └─siren_activation: 3-4        [1, 128]                  --
│    │    └─Linear: 3-5                  [1, 128]                  16,512
│    │    └─siren_activation: 3-6        [1, 128]                  --
│    └─FinerResidualLayer: 2-3           [1, 128]                  --
│    │    └─Linear: 3-7                  [1, 128]                  16,512
│    │    └─siren_activation: 3-8        [1, 128]                  --
│ 

## Gaussian Model and Finer Gaussian

In [19]:
from models.implicit_neural_representations.inr_models.gaussian_model import GaussianModel, GaussianFinerModel

In [20]:
# initialize gaussian model without residual layers
gaussian_model = GaussianModel(
    in_features=2,
    out_features=2,
    hidden_layers=5,
    hidden_features=512,
    scale=30.0,
    weight_init=2.0,
    bias_init=2.0,
    residual_net=False
)

In [21]:
output = gaussian_model(x_dummy)

In [22]:
# Print input and output
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 0.2643,  0.4806],
        [-0.3880, -0.1166],
        [ 0.5267,  0.3416],
        [ 1.0770, -0.5350],
        [-0.4397,  0.7759]])
Output:
tensor([[ 0.1539, -1.1772],
        [-0.2657,  1.9102],
        [ 0.0419,  1.5496],
        [-2.4015, -1.7814],
        [-2.3004, -0.3239]], grad_fn=<MmBackward0>)


In [23]:
model_summary(gaussian_model, input_size=(1, 2))

Layer (type:depth-idx)                             Output Shape              Param #
GaussianModel                                      [1, 2]                    --
├─Sequential: 1-1                                  [1, 2]                    --
│    └─GaussianFourierFeatureTransform: 2-1        [1, 4]                    --
│    └─GaussianLayer: 2-2                          [1, 512]                  --
│    │    └─Linear: 3-1                            [1, 512]                  2,560
│    │    └─gaussian_activation: 3-2               [1, 512]                  --
│    └─GaussianLayer: 2-3                          [1, 512]                  --
│    │    └─Linear: 3-3                            [1, 512]                  262,656
│    │    └─gaussian_activation: 3-4               [1, 512]                  --
│    └─GaussianLayer: 2-4                          [1, 512]                  --
│    │    └─Linear: 3-5                            [1, 512]                  262,656
│    │    └─gaussian_a

In [24]:
gaussian_residual_model = GaussianModel(
    in_features=2,
    out_features=2,
    hidden_layers=5,
    hidden_features=512,
    scale=30.0,
    weight_init=0.1,
    residual_net=True
)

In [25]:
output = gaussian_residual_model(x_dummy)

In [26]:
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 0.2643,  0.4806],
        [-0.3880, -0.1166],
        [ 0.5267,  0.3416],
        [ 1.0770, -0.5350],
        [-0.4397,  0.7759]])
Output:
tensor([[ 0.3805, -0.0921],
        [ 0.2416,  0.0781],
        [ 0.3154,  0.2780],
        [-0.1644, -0.3261],
        [-0.1770, -0.3617]], grad_fn=<MmBackward0>)


In [27]:
model_summary(gaussian_residual_model, input_size=(1, 2))

Layer (type:depth-idx)                             Output Shape              Param #
GaussianModel                                      [1, 2]                    --
├─Sequential: 1-1                                  [1, 2]                    --
│    └─GaussianFourierFeatureTransform: 2-1        [1, 4]                    --
│    └─GaussianLayer: 2-2                          [1, 512]                  --
│    │    └─Linear: 3-1                            [1, 512]                  2,560
│    │    └─gaussian_activation: 3-2               [1, 512]                  --
│    └─GaussianResidualLayer: 2-3                  [1, 512]                  --
│    │    └─Linear: 3-3                            [1, 512]                  262,656
│    │    └─gaussian_activation: 3-4               [1, 512]                  --
│    │    └─Linear: 3-5                            [1, 512]                  262,656
│    │    └─gaussian_activation: 3-6               [1, 512]                  --
│    └─GaussianResidua

In [28]:
gaussian_finer_model = GaussianFinerModel(
    in_features=2,
    out_features=2,
    scale=30.0,
    omega_f=2.5,
    bias_init=5.0,
    weight_init=1.5,
    residual_net=False
)

In [29]:
output = gaussian_finer_model(x_dummy)

In [30]:
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 0.2643,  0.4806],
        [-0.3880, -0.1166],
        [ 0.5267,  0.3416],
        [ 1.0770, -0.5350],
        [-0.4397,  0.7759]])
Output:
tensor([[ 2.4971,  0.7265],
        [-0.3502, -2.3282],
        [ 2.9542,  0.1464],
        [-1.2269,  1.2049],
        [-0.1961,  0.7540]], grad_fn=<MmBackward0>)


In [31]:
model_summary(gaussian_finer_model, input_size=(1, 2))

Layer (type:depth-idx)                             Output Shape              Param #
GaussianFinerModel                                 [1, 2]                    --
├─Sequential: 1-1                                  [1, 2]                    --
│    └─GaussianFourierFeatureTransform: 2-1        [1, 4]                    --
│    └─GaussianFinerLayer: 2-2                     [1, 128]                  --
│    │    └─Linear: 3-1                            [1, 128]                  640
│    │    └─gaussian_activation: 3-2               [1, 128]                  --
│    └─GaussianFinerLayer: 2-3                     [1, 128]                  --
│    │    └─Linear: 3-3                            [1, 128]                  16,512
│    │    └─gaussian_activation: 3-4               [1, 128]                  --
│    └─GaussianFinerLayer: 2-4                     [1, 128]                  --
│    │    └─Linear: 3-5                            [1, 128]                  16,512
│    │    └─gaussian_activ

In [32]:
gaussian_finer_residual_model = GaussianFinerModel(
    in_features=2,
    out_features=2,
    scale=30.0,
    omega_f=2.5,
    bias_init=5.0,
    weight_init=0.1,
    residual_net=True
)

In [33]:
output = gaussian_finer_residual_model(x_dummy)

In [34]:
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 0.2643,  0.4806],
        [-0.3880, -0.1166],
        [ 0.5267,  0.3416],
        [ 1.0770, -0.5350],
        [-0.4397,  0.7759]])
Output:
tensor([[-0.1565,  0.1635],
        [-0.0376,  0.0895],
        [ 0.0418,  0.0296],
        [-0.0700,  0.0542],
        [ 0.0520, -0.1641]], grad_fn=<MmBackward0>)


In [35]:
model_summary(gaussian_finer_residual_model, input_size=(1, 2))

Layer (type:depth-idx)                             Output Shape              Param #
GaussianFinerModel                                 [1, 2]                    --
├─Sequential: 1-1                                  [1, 2]                    --
│    └─GaussianFourierFeatureTransform: 2-1        [1, 4]                    --
│    └─GaussianFinerLayer: 2-2                     [1, 128]                  --
│    │    └─Linear: 3-1                            [1, 128]                  640
│    │    └─gaussian_activation: 3-2               [1, 128]                  --
│    └─GaussianFinerResidualLayer: 2-3             [1, 128]                  --
│    │    └─Linear: 3-3                            [1, 128]                  16,512
│    │    └─gaussian_activation: 3-4               [1, 128]                  --
│    │    └─Linear: 3-5                            [1, 128]                  16,512
│    │    └─gaussian_activation: 3-6               [1, 128]                  --
│    └─GaussianFinerResidu

## MLP MODEL

In [36]:
from models.implicit_neural_representations.inr_models.mlp_model import MLPModel

In [37]:
mlp_model = MLPModel(
    in_features=2,
    out_features=2,
    mapping_type="gauss",
    mapping_dim=4,
    mapping_scale=10,
    hidden_features=128,
    hidden_layers = 5, 
    bias=True,
    weight_init=0.1,
    bias_init=None,
    residual_net=False)

In [38]:
output = mlp_model(x_dummy)

In [39]:
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 0.2643,  0.4806],
        [-0.3880, -0.1166],
        [ 0.5267,  0.3416],
        [ 1.0770, -0.5350],
        [-0.4397,  0.7759]])
Output:
tensor([[-0.0742,  0.0089],
        [-0.0759,  0.0091],
        [-0.0738,  0.0098],
        [-0.0734,  0.0099],
        [-0.0729,  0.0092]], grad_fn=<AddmmBackward0>)


In [40]:
model_summary(mlp_model, input_size=(1, 2))

Layer (type:depth-idx)                             Output Shape              Param #
MLPModel                                           [1, 2]                    --
├─Sequential: 1-1                                  [1, 2]                    --
│    └─GaussianFourierFeatureTransform: 2-1        [1, 4]                    --
│    └─MLPLayer: 2-2                               [1, 128]                  --
│    │    └─Linear: 3-1                            [1, 128]                  640
│    │    └─ReLU: 3-2                              [1, 128]                  --
│    └─MLPLayer: 2-3                               [1, 128]                  --
│    │    └─Linear: 3-3                            [1, 128]                  16,512
│    │    └─ReLU: 3-4                              [1, 128]                  --
│    └─MLPLayer: 2-4                               [1, 128]                  --
│    │    └─Linear: 3-5                            [1, 128]                  16,512
│    │    └─ReLU: 3-6     

In [41]:
mlp_residual_model = MLPModel(
    in_features=2,
    out_features=2,
    mapping_type="gauss",
    mapping_dim=4,
    mapping_scale=10,
    hidden_features=128,
    hidden_layers = 5, 
    bias=True,
    weight_init=0.1,
    bias_init=None,
    residual_net=True)

In [42]:
output = mlp_residual_model(x_dummy)

In [43]:
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 0.2643,  0.4806],
        [-0.3880, -0.1166],
        [ 0.5267,  0.3416],
        [ 1.0770, -0.5350],
        [-0.4397,  0.7759]])
Output:
tensor([[-0.1386,  0.1169],
        [-0.0278,  0.0643],
        [-0.0096,  0.1351],
        [-0.0762,  0.1155],
        [-0.0114,  0.0719]], grad_fn=<AddmmBackward0>)


In [44]:
model_summary(mlp_residual_model, input_size=(1, 2))

Layer (type:depth-idx)                             Output Shape              Param #
MLPModel                                           [1, 2]                    --
├─Sequential: 1-1                                  [1, 2]                    --
│    └─GaussianFourierFeatureTransform: 2-1        [1, 4]                    --
│    └─MLPLayer: 2-2                               [1, 128]                  --
│    │    └─Linear: 3-1                            [1, 128]                  640
│    │    └─ReLU: 3-2                              [1, 128]                  --
│    └─MLPResidualLayer: 2-3                       [1, 128]                  --
│    │    └─Linear: 3-3                            [1, 128]                  16,512
│    │    └─ReLU: 3-4                              [1, 128]                  --
│    │    └─Linear: 3-5                            [1, 128]                  16,512
│    │    └─ReLU: 3-6                              [1, 128]                  --
│    └─MLPResidualLayer: 2

## Wire Models

In [45]:
from models.implicit_neural_representations.inr_models.wire_model import WireModel

In [46]:
wire_model = WireModel(
    in_features=2,
    out_features=2,
    mapping_type="no",
    mapping_dim=4,
    mapping_scale=10,
    hidden_features=128,
    hidden_layers = 5, 
    scale=10.0,
    omega=20.0,
    bias=True,
    weight_init=0.1,
    bias_init=None,
    residual_net=False
)

In [47]:
output = wire_model(x_dummy)

In [48]:
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 0.2643,  0.4806],
        [-0.3880, -0.1166],
        [ 0.5267,  0.3416],
        [ 1.0770, -0.5350],
        [-0.4397,  0.7759]])
Output:
tensor([[ 0.1339+0.3574j,  0.1494+0.7799j],
        [ 0.1624-0.0618j,  0.1188-0.2991j],
        [-0.4735-0.1045j, -0.0401-0.1325j],
        [-0.0520+0.1844j, -0.4341+0.1051j],
        [-0.2633+0.0319j,  0.2726+0.6431j]], grad_fn=<MmBackward0>)


In [49]:
model_summary(wire_model, input_size=(1, 2))

Layer (type:depth-idx)                   Output Shape              Param #
WireModel                                [1, 2]                    --
├─Sequential: 1-1                        [1, 2]                    --
│    └─WireLayer: 2-1                    [1, 128]                  --
│    │    └─Linear: 3-1                  [1, 128]                  384
│    │    └─wire_activation: 3-2         [1, 128]                  --
│    └─WireLayer: 2-2                    [1, 128]                  --
│    │    └─Linear: 3-3                  [1, 128]                  16,512
│    │    └─wire_activation: 3-4         [1, 128]                  --
│    └─WireLayer: 2-3                    [1, 128]                  --
│    │    └─Linear: 3-5                  [1, 128]                  16,512
│    │    └─wire_activation: 3-6         [1, 128]                  --
│    └─WireLayer: 2-4                    [1, 128]                  --
│    │    └─Linear: 3-7                  [1, 128]                  16,512
│ 

In [50]:
wire_residual_model = WireModel(
    in_features=2,
    out_features=2,
    mapping_type="gauss",
    mapping_dim=4,
    mapping_scale=10,
    hidden_features=128,
    hidden_layers = 5,
    scale=10.0,
    omega=20.0,
    bias=True,
    weight_init=0.1,
    bias_init=None,
    residual_net=True
)

In [51]:
output = wire_residual_model(x_dummy)

In [52]:
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 0.2643,  0.4806],
        [-0.3880, -0.1166],
        [ 0.5267,  0.3416],
        [ 1.0770, -0.5350],
        [-0.4397,  0.7759]])
Output:
tensor([[-0.1886-0.2890j,  0.1579-0.2389j],
        [-0.1342-0.0030j,  0.1129-0.0539j],
        [ 0.9763-0.5448j, -0.6174-0.1249j],
        [-0.4644+0.0806j,  0.2385-0.2164j],
        [ 0.1691-0.1164j,  0.3318-0.2280j]], grad_fn=<MmBackward0>)


In [53]:
print(model_summary(wire_residual_model, input_size=(1, 2)))

Layer (type:depth-idx)                             Output Shape              Param #
WireModel                                          [1, 2]                    --
├─Sequential: 1-1                                  [1, 2]                    --
│    └─GaussianFourierFeatureTransform: 2-1        [1, 4]                    --
│    └─WireLayer: 2-2                              [1, 128]                  --
│    │    └─Linear: 3-1                            [1, 128]                  640
│    │    └─wire_activation: 3-2                   [1, 128]                  --
│    └─WireResidualLayer: 2-3                      [1, 128]                  --
│    │    └─Linear: 3-3                            [1, 128]                  16,512
│    │    └─wire_activation: 3-4                   [1, 128]                  --
│    │    └─Linear: 3-5                            [1, 128]                  16,512
│    │    └─wire_activation: 3-6                   [1, 128]                  --
│    └─WireResidualLayer: 