## SIREN and FINER MODEL

In [1]:
import torch
from models.implicit_neural_representations.inr_models.siren_model import SirenModel, FinerModel

In [2]:
x_dummy = torch.randn(5, 2)

In [3]:
# initialize siren model without residual layers
siren_model = SirenModel(
    in_features=2,
    out_features=2,
    hidden_layers=5,
    hidden_features=512,
    first_omega_0=30.0,
    hidden_omega_0=30.0,
    residual_net=False
)

In [4]:
output = siren_model(x_dummy)

In [5]:
# Print input and output
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[-0.6986, -0.1619],
        [-0.3133,  0.4067],
        [ 0.4126,  0.2592],
        [ 0.2147,  0.2995],
        [-0.6245, -0.6845]])
Output:
tensor([[-0.0139,  0.0276],
        [-0.0022,  0.0550],
        [-0.0090,  0.0697],
        [-0.0237,  0.0379],
        [-0.0088,  0.0527]], grad_fn=<AddmmBackward0>)


In [6]:
finer_model = FinerModel(
    in_features=2,
    out_features=2,
    bias=True,
    hidden_layers=5,
    hidden_features=128,
    first_omega_0=30.,
    hidden_omega_0=30.,
    first_bias=10,
    hidden_bias=10,
    residual_net=False
)

In [7]:
output = finer_model(x_dummy)

In [8]:
# Print input and output
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[-0.6986, -0.1619],
        [-0.3133,  0.4067],
        [ 0.4126,  0.2592],
        [ 0.2147,  0.2995],
        [-0.6245, -0.6845]])
Output:
tensor([[-0.0127, -0.0748],
        [-0.0118, -0.0746],
        [-0.0124, -0.0743],
        [-0.0123, -0.0748],
        [-0.0118, -0.0741]], grad_fn=<AddmmBackward0>)


In [9]:
siren_residual_model = SirenModel(
    in_features=2,
    out_features=2,
    hidden_layers=5,
    hidden_features=512,
    first_omega_0=30.0,
    hidden_omega_0=30.0,
    residual_net=True
)

In [10]:
output = siren_residual_model(x_dummy)

In [11]:
# Print input and output
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[-0.6986, -0.1619],
        [-0.3133,  0.4067],
        [ 0.4126,  0.2592],
        [ 0.2147,  0.2995],
        [-0.6245, -0.6845]])
Output:
tensor([[-0.1467,  0.1285],
        [-0.0211, -0.1325],
        [ 0.1184, -0.1266],
        [ 0.0400, -0.0928],
        [-0.0412, -0.0479]], grad_fn=<AddmmBackward0>)


In [12]:
finer_residual_model = FinerModel( 
    in_features=2,
    out_features=2,
    bias=True,
    hidden_layers=5,
    hidden_features=128,
    first_omega_0=30.,
    hidden_omega_0=30.,
    first_bias=10,
    hidden_bias=10,
    residual_net=True
)

In [13]:
output = finer_residual_model(x_dummy)

In [14]:
# Print input and output
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[-0.6986, -0.1619],
        [-0.3133,  0.4067],
        [ 0.4126,  0.2592],
        [ 0.2147,  0.2995],
        [-0.6245, -0.6845]])
Output:
tensor([[ 0.0014, -0.1981],
        [ 0.0493, -0.1526],
        [-0.0993, -0.1100],
        [-0.0830, -0.0592],
        [-0.0248, -0.0688]], grad_fn=<AddmmBackward0>)
