In [1]:
import torch
from helpers import model_summary
x_dummy = torch.randn(5, 2)

## SIREN and FINER MODEL

In [2]:
from models.implicit_neural_representations.inr_models.siren_model import SirenModel, FinerModel

In [3]:
# initialize siren model without residual layers
siren_model = SirenModel(
    in_features=2,
    out_features=2,
    hidden_layers=5,
    hidden_features=512,
    first_omega_0=30.0,
    hidden_omega_0=30.0,
    residual_net=False
)

In [4]:
output = siren_model(x_dummy)

In [5]:
# Print input and output
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[-0.8798,  0.3790],
        [-0.0098, -0.8997],
        [ 2.0947, -0.1007],
        [ 0.0061, -0.4889],
        [-1.0419, -0.2032]])
Output:
tensor([[0.0140, 0.0267],
        [0.0375, 0.0390],
        [0.0389, 0.0505],
        [0.0122, 0.0062],
        [0.0059, 0.0591]], grad_fn=<MmBackward0>)


In [45]:
model_summary(siren_model, input_size=(1, 2))

Layer (type:depth-idx)                   Output Shape              Param #
SirenModel                               [1, 2]                    --
├─Sequential: 1-1                        [1, 2]                    --
│    └─SirenLayer: 2-1                   [1, 512]                  --
│    │    └─Linear: 3-1                  [1, 512]                  1,536
│    │    └─siren_activation: 3-2        [1, 512]                  --
│    └─SirenLayer: 2-2                   [1, 512]                  --
│    │    └─Linear: 3-3                  [1, 512]                  262,656
│    │    └─siren_activation: 3-4        [1, 512]                  --
│    └─SirenLayer: 2-3                   [1, 512]                  --
│    │    └─Linear: 3-5                  [1, 512]                  262,656
│    │    └─siren_activation: 3-6        [1, 512]                  --
│    └─SirenLayer: 2-4                   [1, 512]                  --
│    │    └─Linear: 3-7                  [1, 512]                  262,6

Layer (type:depth-idx)                   Output Shape              Param #
SirenModel                               [1, 2]                    --
├─Sequential: 1-1                        [1, 2]                    --
│    └─SirenLayer: 2-1                   [1, 512]                  --
│    │    └─Linear: 3-1                  [1, 512]                  1,536
│    │    └─siren_activation: 3-2        [1, 512]                  --
│    └─SirenLayer: 2-2                   [1, 512]                  --
│    │    └─Linear: 3-3                  [1, 512]                  262,656
│    │    └─siren_activation: 3-4        [1, 512]                  --
│    └─SirenLayer: 2-3                   [1, 512]                  --
│    │    └─Linear: 3-5                  [1, 512]                  262,656
│    │    └─siren_activation: 3-6        [1, 512]                  --
│    └─SirenLayer: 2-4                   [1, 512]                  --
│    │    └─Linear: 3-7                  [1, 512]                  262,6

In [7]:
finer_model = FinerModel(
    in_features=2,
    out_features=2,
    bias=True,
    hidden_layers=5,
    hidden_features=128,
    first_omega_0=30.,
    hidden_omega_0=30.,
    first_k=10,
    hidden_k=10,
    residual_net=False
)

In [8]:
output = finer_model(x_dummy)

In [9]:
# Print input and output
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[-0.8798,  0.3790],
        [-0.0098, -0.8997],
        [ 2.0947, -0.1007],
        [ 0.0061, -0.4889],
        [-1.0419, -0.2032]])
Output:
tensor([[-0.0239,  0.0082],
        [-0.0550,  0.0266],
        [ 0.0222, -0.0241],
        [-0.0317,  0.0058],
        [-0.0507,  0.0232]], grad_fn=<MmBackward0>)


In [10]:
model_summary(finer_model, input_size=(1, 2))

Layer (type:depth-idx)                   Output Shape              Param #
FinerModel                               [1, 2]                    --
├─Sequential: 1-1                        [1, 2]                    --
│    └─FinerLayer: 2-1                   [1, 128]                  --
│    │    └─Linear: 3-1                  [1, 128]                  384
│    │    └─siren_activation: 3-2        [1, 128]                  --
│    └─FinerLayer: 2-2                   [1, 128]                  --
│    │    └─Linear: 3-3                  [1, 128]                  16,512
│    │    └─siren_activation: 3-4        [1, 128]                  --
│    └─FinerLayer: 2-3                   [1, 128]                  --
│    │    └─Linear: 3-5                  [1, 128]                  16,512
│    │    └─siren_activation: 3-6        [1, 128]                  --
│    └─FinerLayer: 2-4                   [1, 128]                  --
│    │    └─Linear: 3-7                  [1, 128]                  16,512
│ 

Layer (type:depth-idx)                   Output Shape              Param #
FinerModel                               [1, 2]                    --
├─Sequential: 1-1                        [1, 2]                    --
│    └─FinerLayer: 2-1                   [1, 128]                  --
│    │    └─Linear: 3-1                  [1, 128]                  384
│    │    └─siren_activation: 3-2        [1, 128]                  --
│    └─FinerLayer: 2-2                   [1, 128]                  --
│    │    └─Linear: 3-3                  [1, 128]                  16,512
│    │    └─siren_activation: 3-4        [1, 128]                  --
│    └─FinerLayer: 2-3                   [1, 128]                  --
│    │    └─Linear: 3-5                  [1, 128]                  16,512
│    │    └─siren_activation: 3-6        [1, 128]                  --
│    └─FinerLayer: 2-4                   [1, 128]                  --
│    │    └─Linear: 3-7                  [1, 128]                  16,512
│ 

In [11]:
siren_residual_model = SirenModel(
    in_features=2,
    out_features=2,
    hidden_layers=5,
    hidden_features=512,
    first_omega_0=30.0,
    hidden_omega_0=30.0,
    residual_net=True
)

In [12]:
output = siren_residual_model(x_dummy)

In [13]:
# Print input and output
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[-0.8798,  0.3790],
        [-0.0098, -0.8997],
        [ 2.0947, -0.1007],
        [ 0.0061, -0.4889],
        [-1.0419, -0.2032]])
Output:
tensor([[-0.0366, -0.0571],
        [-0.0365,  0.0362],
        [-0.0642, -0.0379],
        [ 0.0017, -0.0269],
        [-0.0124,  0.0504]], grad_fn=<MmBackward0>)


In [14]:
model_summary(siren_residual_model, input_size=(1, 2))

Layer (type:depth-idx)                   Output Shape              Param #
SirenModel                               [1, 2]                    --
├─Sequential: 1-1                        [1, 2]                    --
│    └─SirenLayer: 2-1                   [1, 512]                  --
│    │    └─Linear: 3-1                  [1, 512]                  1,536
│    │    └─siren_activation: 3-2        [1, 512]                  --
│    └─SirenResidualLayer: 2-2           [1, 512]                  --
│    │    └─Linear: 3-3                  [1, 512]                  262,656
│    │    └─siren_activation: 3-4        [1, 512]                  --
│    │    └─Linear: 3-5                  [1, 512]                  262,656
│    │    └─siren_activation: 3-6        [1, 512]                  --
│    └─SirenResidualLayer: 2-3           [1, 512]                  --
│    │    └─Linear: 3-7                  [1, 512]                  262,656
│    │    └─siren_activation: 3-8        [1, 512]                  

Layer (type:depth-idx)                   Output Shape              Param #
SirenModel                               [1, 2]                    --
├─Sequential: 1-1                        [1, 2]                    --
│    └─SirenLayer: 2-1                   [1, 512]                  --
│    │    └─Linear: 3-1                  [1, 512]                  1,536
│    │    └─siren_activation: 3-2        [1, 512]                  --
│    └─SirenResidualLayer: 2-2           [1, 512]                  --
│    │    └─Linear: 3-3                  [1, 512]                  262,656
│    │    └─siren_activation: 3-4        [1, 512]                  --
│    │    └─Linear: 3-5                  [1, 512]                  262,656
│    │    └─siren_activation: 3-6        [1, 512]                  --
│    └─SirenResidualLayer: 2-3           [1, 512]                  --
│    │    └─Linear: 3-7                  [1, 512]                  262,656
│    │    └─siren_activation: 3-8        [1, 512]                  

In [15]:
finer_residual_model = FinerModel( 
    in_features=2,
    out_features=2,
    bias=True,
    hidden_layers=5,
    hidden_features=128,
    first_omega_0=30.,
    hidden_omega_0=30.,
    first_k=10,
    hidden_k=10,
    residual_net=True
)

In [16]:
output = finer_residual_model(x_dummy)

In [17]:
# Print input and output
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[-0.8798,  0.3790],
        [-0.0098, -0.8997],
        [ 2.0947, -0.1007],
        [ 0.0061, -0.4889],
        [-1.0419, -0.2032]])
Output:
tensor([[ 0.0049,  0.0167],
        [ 0.0325, -0.0285],
        [ 0.0161,  0.0168],
        [ 0.0296,  0.0229],
        [ 0.0170, -0.0005]], grad_fn=<MmBackward0>)


In [18]:
model_summary(finer_residual_model, input_size=(1, 2))

Layer (type:depth-idx)                   Output Shape              Param #
FinerModel                               [1, 2]                    --
├─Sequential: 1-1                        [1, 2]                    --
│    └─FinerLayer: 2-1                   [1, 128]                  --
│    │    └─Linear: 3-1                  [1, 128]                  384
│    │    └─siren_activation: 3-2        [1, 128]                  --
│    └─FinerResidualLayer: 2-2           [1, 128]                  --
│    │    └─Linear: 3-3                  [1, 128]                  16,512
│    │    └─siren_activation: 3-4        [1, 128]                  --
│    │    └─Linear: 3-5                  [1, 128]                  16,512
│    │    └─siren_activation: 3-6        [1, 128]                  --
│    └─FinerResidualLayer: 2-3           [1, 128]                  --
│    │    └─Linear: 3-7                  [1, 128]                  16,512
│    │    └─siren_activation: 3-8        [1, 128]                  --
│ 

Layer (type:depth-idx)                   Output Shape              Param #
FinerModel                               [1, 2]                    --
├─Sequential: 1-1                        [1, 2]                    --
│    └─FinerLayer: 2-1                   [1, 128]                  --
│    │    └─Linear: 3-1                  [1, 128]                  384
│    │    └─siren_activation: 3-2        [1, 128]                  --
│    └─FinerResidualLayer: 2-2           [1, 128]                  --
│    │    └─Linear: 3-3                  [1, 128]                  16,512
│    │    └─siren_activation: 3-4        [1, 128]                  --
│    │    └─Linear: 3-5                  [1, 128]                  16,512
│    │    └─siren_activation: 3-6        [1, 128]                  --
│    └─FinerResidualLayer: 2-3           [1, 128]                  --
│    │    └─Linear: 3-7                  [1, 128]                  16,512
│    │    └─siren_activation: 3-8        [1, 128]                  --
│ 

## Gaussian Model and Finer Gaussian

In [19]:
from models.implicit_neural_representations.inr_models.gaussian_model import GaussianModel, GaussianFinerModel

In [20]:
# initialize gaussian model without residual layers
gaussian_model = GaussianModel(
    in_features=2,
    out_features=2,
    hidden_layers=5,
    hidden_features=512,
    scale=30.0,
    weight_init=2.0,
    bias_init=2.0,
    residual_net=False
)

In [21]:
output = gaussian_model(x_dummy)

In [22]:
# Print input and output
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[-0.8798,  0.3790],
        [-0.0098, -0.8997],
        [ 2.0947, -0.1007],
        [ 0.0061, -0.4889],
        [-1.0419, -0.2032]])
Output:
tensor([[-1.9259, -0.2457],
        [ 3.0072, -3.3295],
        [ 0.4148, -0.1276],
        [ 1.3377, -3.3764],
        [-3.0452,  3.2900]], grad_fn=<MmBackward0>)


In [23]:
model_summary(gaussian_model, input_size=(1, 2))

Layer (type:depth-idx)                             Output Shape              Param #
GaussianModel                                      [1, 2]                    --
├─Sequential: 1-1                                  [1, 2]                    --
│    └─GaussianFourierFeatureTransform: 2-1        [1, 4]                    --
│    └─GaussianLayer: 2-2                          [1, 512]                  --
│    │    └─Linear: 3-1                            [1, 512]                  2,560
│    │    └─gaussian_activation: 3-2               [1, 512]                  --
│    └─GaussianLayer: 2-3                          [1, 512]                  --
│    │    └─Linear: 3-3                            [1, 512]                  262,656
│    │    └─gaussian_activation: 3-4               [1, 512]                  --
│    └─GaussianLayer: 2-4                          [1, 512]                  --
│    │    └─Linear: 3-5                            [1, 512]                  262,656
│    │    └─gaussian_a

Layer (type:depth-idx)                             Output Shape              Param #
GaussianModel                                      [1, 2]                    --
├─Sequential: 1-1                                  [1, 2]                    --
│    └─GaussianFourierFeatureTransform: 2-1        [1, 4]                    --
│    └─GaussianLayer: 2-2                          [1, 512]                  --
│    │    └─Linear: 3-1                            [1, 512]                  2,560
│    │    └─gaussian_activation: 3-2               [1, 512]                  --
│    └─GaussianLayer: 2-3                          [1, 512]                  --
│    │    └─Linear: 3-3                            [1, 512]                  262,656
│    │    └─gaussian_activation: 3-4               [1, 512]                  --
│    └─GaussianLayer: 2-4                          [1, 512]                  --
│    │    └─Linear: 3-5                            [1, 512]                  262,656
│    │    └─gaussian_a

In [24]:
gaussian_residual_model = GaussianModel(
    in_features=2,
    out_features=2,
    hidden_layers=5,
    hidden_features=512,
    scale=30.0,
    weight_init=0.1,
    residual_net=True
)

In [25]:
output = gaussian_residual_model(x_dummy)

In [26]:
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[-0.8798,  0.3790],
        [-0.0098, -0.8997],
        [ 2.0947, -0.1007],
        [ 0.0061, -0.4889],
        [-1.0419, -0.2032]])
Output:
tensor([[-0.2840, -0.1326],
        [ 0.0570, -0.0336],
        [ 0.3011,  0.3241],
        [ 0.6340,  0.0129],
        [ 0.5427,  0.0706]], grad_fn=<MmBackward0>)


In [27]:
model_summary(gaussian_residual_model, input_size=(1, 2))

Layer (type:depth-idx)                             Output Shape              Param #
GaussianModel                                      [1, 2]                    --
├─Sequential: 1-1                                  [1, 2]                    --
│    └─GaussianFourierFeatureTransform: 2-1        [1, 4]                    --
│    └─GaussianLayer: 2-2                          [1, 512]                  --
│    │    └─Linear: 3-1                            [1, 512]                  2,560
│    │    └─gaussian_activation: 3-2               [1, 512]                  --
│    └─GaussianResidualLayer: 2-3                  [1, 512]                  --
│    │    └─Linear: 3-3                            [1, 512]                  262,656
│    │    └─gaussian_activation: 3-4               [1, 512]                  --
│    │    └─Linear: 3-5                            [1, 512]                  262,656
│    │    └─gaussian_activation: 3-6               [1, 512]                  --
│    └─GaussianResidua

Layer (type:depth-idx)                             Output Shape              Param #
GaussianModel                                      [1, 2]                    --
├─Sequential: 1-1                                  [1, 2]                    --
│    └─GaussianFourierFeatureTransform: 2-1        [1, 4]                    --
│    └─GaussianLayer: 2-2                          [1, 512]                  --
│    │    └─Linear: 3-1                            [1, 512]                  2,560
│    │    └─gaussian_activation: 3-2               [1, 512]                  --
│    └─GaussianResidualLayer: 2-3                  [1, 512]                  --
│    │    └─Linear: 3-3                            [1, 512]                  262,656
│    │    └─gaussian_activation: 3-4               [1, 512]                  --
│    │    └─Linear: 3-5                            [1, 512]                  262,656
│    │    └─gaussian_activation: 3-6               [1, 512]                  --
│    └─GaussianResidua

In [28]:
gaussian_finer_model = GaussianFinerModel(
    in_features=2,
    out_features=2,
    scale=30.0,
    omega_f=2.5,
    bias_init=5.0,
    weight_init=1.5,
    residual_net=False
)

In [29]:
output = gaussian_finer_model(x_dummy)

In [30]:
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[-0.8798,  0.3790],
        [-0.0098, -0.8997],
        [ 2.0947, -0.1007],
        [ 0.0061, -0.4889],
        [-1.0419, -0.2032]])
Output:
tensor([[-2.0869, -1.7512],
        [ 2.2883, -0.2161],
        [-1.9643,  0.7797],
        [ 4.3409,  1.0523],
        [ 1.6237,  1.5996]], grad_fn=<MmBackward0>)


In [31]:
model_summary(gaussian_finer_model, input_size=(1, 2))

Layer (type:depth-idx)                             Output Shape              Param #
GaussianFinerModel                                 [1, 2]                    --
├─Sequential: 1-1                                  [1, 2]                    --
│    └─GaussianFourierFeatureTransform: 2-1        [1, 4]                    --
│    └─GaussianFinerLayer: 2-2                     [1, 128]                  --
│    │    └─Linear: 3-1                            [1, 128]                  640
│    │    └─gaussian_activation: 3-2               [1, 128]                  --
│    └─GaussianFinerLayer: 2-3                     [1, 128]                  --
│    │    └─Linear: 3-3                            [1, 128]                  16,512
│    │    └─gaussian_activation: 3-4               [1, 128]                  --
│    └─GaussianFinerLayer: 2-4                     [1, 128]                  --
│    │    └─Linear: 3-5                            [1, 128]                  16,512
│    │    └─gaussian_activ

Layer (type:depth-idx)                             Output Shape              Param #
GaussianFinerModel                                 [1, 2]                    --
├─Sequential: 1-1                                  [1, 2]                    --
│    └─GaussianFourierFeatureTransform: 2-1        [1, 4]                    --
│    └─GaussianFinerLayer: 2-2                     [1, 128]                  --
│    │    └─Linear: 3-1                            [1, 128]                  640
│    │    └─gaussian_activation: 3-2               [1, 128]                  --
│    └─GaussianFinerLayer: 2-3                     [1, 128]                  --
│    │    └─Linear: 3-3                            [1, 128]                  16,512
│    │    └─gaussian_activation: 3-4               [1, 128]                  --
│    └─GaussianFinerLayer: 2-4                     [1, 128]                  --
│    │    └─Linear: 3-5                            [1, 128]                  16,512
│    │    └─gaussian_activ

In [32]:
gaussian_finer_residual_model = GaussianFinerModel(
    in_features=2,
    out_features=2,
    scale=30.0,
    omega_f=2.5,
    bias_init=5.0,
    weight_init=0.1,
    residual_net=True
)

In [33]:
output = gaussian_finer_residual_model(x_dummy)

In [34]:
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[-0.8798,  0.3790],
        [-0.0098, -0.8997],
        [ 2.0947, -0.1007],
        [ 0.0061, -0.4889],
        [-1.0419, -0.2032]])
Output:
tensor([[-0.0456,  0.1968],
        [-0.1735,  0.0115],
        [ 0.1207, -0.0982],
        [-0.1311,  0.2900],
        [-0.0350,  0.0712]], grad_fn=<MmBackward0>)


In [35]:
model_summary(gaussian_finer_residual_model, input_size=(1, 2))

Layer (type:depth-idx)                             Output Shape              Param #
GaussianFinerModel                                 [1, 2]                    --
├─Sequential: 1-1                                  [1, 2]                    --
│    └─GaussianFourierFeatureTransform: 2-1        [1, 4]                    --
│    └─GaussianFinerLayer: 2-2                     [1, 128]                  --
│    │    └─Linear: 3-1                            [1, 128]                  640
│    │    └─gaussian_activation: 3-2               [1, 128]                  --
│    └─GaussianFinerResidualLayer: 2-3             [1, 128]                  --
│    │    └─Linear: 3-3                            [1, 128]                  16,512
│    │    └─gaussian_activation: 3-4               [1, 128]                  --
│    │    └─Linear: 3-5                            [1, 128]                  16,512
│    │    └─gaussian_activation: 3-6               [1, 128]                  --
│    └─GaussianFinerResidu

Layer (type:depth-idx)                             Output Shape              Param #
GaussianFinerModel                                 [1, 2]                    --
├─Sequential: 1-1                                  [1, 2]                    --
│    └─GaussianFourierFeatureTransform: 2-1        [1, 4]                    --
│    └─GaussianFinerLayer: 2-2                     [1, 128]                  --
│    │    └─Linear: 3-1                            [1, 128]                  640
│    │    └─gaussian_activation: 3-2               [1, 128]                  --
│    └─GaussianFinerResidualLayer: 2-3             [1, 128]                  --
│    │    └─Linear: 3-3                            [1, 128]                  16,512
│    │    └─gaussian_activation: 3-4               [1, 128]                  --
│    │    └─Linear: 3-5                            [1, 128]                  16,512
│    │    └─gaussian_activation: 3-6               [1, 128]                  --
│    └─GaussianFinerResidu

## MLP MODEL

In [36]:
from models.implicit_neural_representations.inr_models.mlp_model import MLPModel

In [37]:
mlp_model = MLPModel(
    in_features=2,
    out_features=2,
    mapping_type="gauss",
    mapping_dim=4,
    mapping_scale=10,
    hidden_features=128,
    hidden_layers = 5, 
    bias=True,
    weight_init=0.1,
    bias_init=None,
    residual_net=False)

In [38]:
output = mlp_model(x_dummy)

In [39]:
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[-0.8798,  0.3790],
        [-0.0098, -0.8997],
        [ 2.0947, -0.1007],
        [ 0.0061, -0.4889],
        [-1.0419, -0.2032]])
Output:
tensor([[0.0951, 0.0301],
        [0.0949, 0.0318],
        [0.0948, 0.0303],
        [0.0959, 0.0303],
        [0.0950, 0.0300]], grad_fn=<AddmmBackward0>)


In [40]:
model_summary(mlp_model, input_size=(1, 2))

Layer (type:depth-idx)                             Output Shape              Param #
MLPModel                                           [1, 2]                    --
├─Sequential: 1-1                                  [1, 2]                    --
│    └─GaussianFourierFeatureTransform: 2-1        [1, 4]                    --
│    └─MLPLayer: 2-2                               [1, 128]                  --
│    │    └─Linear: 3-1                            [1, 128]                  640
│    │    └─ReLU: 3-2                              [1, 128]                  --
│    └─MLPLayer: 2-3                               [1, 128]                  --
│    │    └─Linear: 3-3                            [1, 128]                  16,512
│    │    └─ReLU: 3-4                              [1, 128]                  --
│    └─MLPLayer: 2-4                               [1, 128]                  --
│    │    └─Linear: 3-5                            [1, 128]                  16,512
│    │    └─ReLU: 3-6     

Layer (type:depth-idx)                             Output Shape              Param #
MLPModel                                           [1, 2]                    --
├─Sequential: 1-1                                  [1, 2]                    --
│    └─GaussianFourierFeatureTransform: 2-1        [1, 4]                    --
│    └─MLPLayer: 2-2                               [1, 128]                  --
│    │    └─Linear: 3-1                            [1, 128]                  640
│    │    └─ReLU: 3-2                              [1, 128]                  --
│    └─MLPLayer: 2-3                               [1, 128]                  --
│    │    └─Linear: 3-3                            [1, 128]                  16,512
│    │    └─ReLU: 3-4                              [1, 128]                  --
│    └─MLPLayer: 2-4                               [1, 128]                  --
│    │    └─Linear: 3-5                            [1, 128]                  16,512
│    │    └─ReLU: 3-6     

In [41]:
mlp_residual_model = MLPModel(
    in_features=2,
    out_features=2,
    mapping_type="gauss",
    mapping_dim=4,
    mapping_scale=10,
    hidden_features=128,
    hidden_layers = 5, 
    bias=True,
    weight_init=0.1,
    bias_init=None,
    residual_net=True)

In [42]:
output = mlp_residual_model(x_dummy)

In [43]:
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[-0.8798,  0.3790],
        [-0.0098, -0.8997],
        [ 2.0947, -0.1007],
        [ 0.0061, -0.4889],
        [-1.0419, -0.2032]])
Output:
tensor([[-0.1502, -0.3982],
        [-0.0654, -0.2902],
        [-0.1168, -0.3392],
        [-0.1001, -0.3710],
        [-0.0913, -0.3534]], grad_fn=<AddmmBackward0>)


In [44]:
model_summary(mlp_residual_model, input_size=(1, 2))

Layer (type:depth-idx)                             Output Shape              Param #
MLPModel                                           [1, 2]                    --
├─Sequential: 1-1                                  [1, 2]                    --
│    └─GaussianFourierFeatureTransform: 2-1        [1, 4]                    --
│    └─MLPLayer: 2-2                               [1, 128]                  --
│    │    └─Linear: 3-1                            [1, 128]                  640
│    │    └─ReLU: 3-2                              [1, 128]                  --
│    └─MLPResidualLayer: 2-3                       [1, 128]                  --
│    │    └─Linear: 3-3                            [1, 128]                  16,512
│    │    └─ReLU: 3-4                              [1, 128]                  --
│    │    └─Linear: 3-5                            [1, 128]                  16,512
│    │    └─ReLU: 3-6                              [1, 128]                  --
│    └─MLPResidualLayer: 2

Layer (type:depth-idx)                             Output Shape              Param #
MLPModel                                           [1, 2]                    --
├─Sequential: 1-1                                  [1, 2]                    --
│    └─GaussianFourierFeatureTransform: 2-1        [1, 4]                    --
│    └─MLPLayer: 2-2                               [1, 128]                  --
│    │    └─Linear: 3-1                            [1, 128]                  640
│    │    └─ReLU: 3-2                              [1, 128]                  --
│    └─MLPResidualLayer: 2-3                       [1, 128]                  --
│    │    └─Linear: 3-3                            [1, 128]                  16,512
│    │    └─ReLU: 3-4                              [1, 128]                  --
│    │    └─Linear: 3-5                            [1, 128]                  16,512
│    │    └─ReLU: 3-6                              [1, 128]                  --
│    └─MLPResidualLayer: 2