In [1]:
import torch
from helpers import model_summary
x_dummy = torch.tensor([[90.0, 180.0],
                        [-90.0,180.0],
                        [90.0,180.0],
                        [0.0, 180.0]])

In [2]:
print(x_dummy)

tensor([[ 90., 180.],
        [-90., 180.],
        [ 90., 180.],
        [  0., 180.]])


## SIREN and FINER MODEL

In [3]:
from models.implicit_neural_representations.inr_models.siren_model import SirenModel, FinerModel

In [4]:
# initialize siren model without residual layers
siren_model = SirenModel(
    in_features=2,
    out_features=2,
    hidden_layers=5,
    hidden_features=512,
    first_omega_0=30.0,
    hidden_omega_0=30.0,
    dropout=0.1,
    residual_net=False,
    encoding='dfs',
    r_min=0.001,
    r_max=1.0,
    scale=[10, 10]
)

In [5]:
output = siren_model(x_dummy)

In [6]:
# Print input and output
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 90., 180.],
        [-90., 180.],
        [ 90., 180.],
        [  0., 180.]])
Output:
tensor([[ 0.0152,  0.0612],
        [-0.0380, -0.0200],
        [ 0.0101, -0.0042],
        [-0.0653,  0.1012]], grad_fn=<MmBackward0>)


In [7]:
model_summary(siren_model, input_size=(1, 2))

Layer (type:depth-idx)                        Output Shape              Param #
SirenModel                                    [1, 2]                    --
├─SphericalFourierFeatureTransform: 1-1       [1, 440]                  --
├─Sequential: 1-2                             [1, 2]                    --
│    └─SirenLayer: 2-1                        [1, 512]                  --
│    │    └─Linear: 3-1                       [1, 512]                  225,792
│    │    └─siren_activation: 3-2             [1, 512]                  --
│    │    └─Identity: 3-3                     [1, 512]                  --
│    └─SirenLayer: 2-2                        [1, 512]                  --
│    │    └─Linear: 3-4                       [1, 512]                  262,656
│    │    └─siren_activation: 3-5             [1, 512]                  --
│    │    └─Dropout: 3-6                      [1, 512]                  --
│    └─SirenLayer: 2-3                        [1, 512]                  --
│    │    

In [8]:
finer_model = FinerModel(
    in_features=2,
    out_features=2,
    bias=True,
    hidden_layers=5,
    hidden_features=128,
    first_omega_0=30.,
    hidden_omega_0=30.,
    first_k=10,
    hidden_k=10,
    dropout=0.1,
    residual_net=False,
    encoding='dfs',
    r_min=0.001,
    r_max=1.0,
    scale=[10, 10]
)

In [9]:
output = finer_model(x_dummy)

In [10]:
# Print input and output
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 90., 180.],
        [-90., 180.],
        [ 90., 180.],
        [  0., 180.]])
Output:
tensor([[ 0.0051,  0.0128],
        [-0.0384, -0.0114],
        [-0.0415,  0.0118],
        [ 0.0034,  0.0263]], grad_fn=<MmBackward0>)


In [11]:
model_summary(finer_model, input_size=(1, 2))

Layer (type:depth-idx)                        Output Shape              Param #
FinerModel                                    [1, 2]                    --
├─SphericalFourierFeatureTransform: 1-1       [1, 440]                  --
├─Sequential: 1-2                             [1, 2]                    --
│    └─FinerLayer: 2-1                        [1, 128]                  --
│    │    └─Linear: 3-1                       [1, 128]                  56,448
│    │    └─siren_activation: 3-2             [1, 128]                  --
│    │    └─Identity: 3-3                     [1, 128]                  --
│    └─FinerLayer: 2-2                        [1, 128]                  --
│    │    └─Linear: 3-4                       [1, 128]                  16,512
│    │    └─siren_activation: 3-5             [1, 128]                  --
│    │    └─Dropout: 3-6                      [1, 128]                  --
│    └─FinerLayer: 2-3                        [1, 128]                  --
│    │    └─

In [12]:
siren_residual_model = SirenModel(
    in_features=2,
    out_features=2,
    hidden_layers=5,
    hidden_features=512,
    first_omega_0=30.0,
    hidden_omega_0=30.0,
    dropout=0.1,
    residual_net=True,
    encoding='dfs',
    r_min=0.001,
    r_max=1.0,
    scale=[10, 10]
)

In [13]:
output = siren_residual_model(x_dummy)

In [14]:
# Print input and output
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 90., 180.],
        [-90., 180.],
        [ 90., 180.],
        [  0., 180.]])
Output:
tensor([[ 0.0172, -0.0098],
        [-0.0774, -0.0706],
        [ 0.0803,  0.0312],
        [-0.0602,  0.0245]], grad_fn=<MmBackward0>)


In [15]:
model_summary(siren_residual_model, input_size=(1, 2))

Layer (type:depth-idx)                        Output Shape              Param #
SirenModel                                    [1, 2]                    --
├─SphericalFourierFeatureTransform: 1-1       [1, 440]                  --
├─Sequential: 1-2                             [1, 2]                    --
│    └─SirenLayer: 2-1                        [1, 512]                  --
│    │    └─Linear: 3-1                       [1, 512]                  225,792
│    │    └─siren_activation: 3-2             [1, 512]                  --
│    │    └─Identity: 3-3                     [1, 512]                  --
│    └─SirenResidualLayer: 2-2                [1, 512]                  --
│    │    └─Linear: 3-4                       [1, 512]                  262,656
│    │    └─siren_activation: 3-5             [1, 512]                  --
│    │    └─Linear: 3-6                       [1, 512]                  262,656
│    │    └─siren_activation: 3-7             [1, 512]                  --
│    

In [16]:
finer_residual_model = FinerModel( 
    in_features=2,
    out_features=2,
    bias=True,
    hidden_layers=5,
    hidden_features=128,
    first_omega_0=30.,
    hidden_omega_0=30.,
    first_k=10,
    hidden_k=10,
    dropout=0.1,
    residual_net=True,
    encoding='dfs',
    r_min=0.001,
    r_max=1.0,
    scale=[10, 10]
)

In [17]:
output = finer_residual_model(x_dummy)

In [18]:
# Print input and output
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 90., 180.],
        [-90., 180.],
        [ 90., 180.],
        [  0., 180.]])
Output:
tensor([[ 0.0013, -0.0907],
        [ 0.0318,  0.0336],
        [-0.0539, -0.0096],
        [ 0.0213,  0.0025]], grad_fn=<MmBackward0>)


In [19]:
model_summary(finer_residual_model, input_size=(1, 2))

Layer (type:depth-idx)                        Output Shape              Param #
FinerModel                                    [1, 2]                    --
├─SphericalFourierFeatureTransform: 1-1       [1, 440]                  --
├─Sequential: 1-2                             [1, 2]                    --
│    └─FinerLayer: 2-1                        [1, 128]                  --
│    │    └─Linear: 3-1                       [1, 128]                  56,448
│    │    └─siren_activation: 3-2             [1, 128]                  --
│    │    └─Identity: 3-3                     [1, 128]                  --
│    └─FinerResidualLayer: 2-2                [1, 128]                  --
│    │    └─Linear: 3-4                       [1, 128]                  16,512
│    │    └─siren_activation: 3-5             [1, 128]                  --
│    │    └─Linear: 3-6                       [1, 128]                  16,512
│    │    └─siren_activation: 3-7             [1, 128]                  --
│    │  

## Gaussian Model and Finer Gaussian

In [20]:
from models.implicit_neural_representations.inr_models.gaussian_model import GaussianModel, GaussianFinerModel

In [21]:
# initialize gaussian model without residual layers
gaussian_model = GaussianModel(
    in_features=2,
    out_features=2,
    hidden_layers=5,
    hidden_features=512,
    scale_gaussian=30.0,
    weight_init=2.0,
    bias_init=2.0,
    dropout=0.1,
    residual_net=False,
    encoding='dfs',
    r_min=0.001,
    r_max=1.0,
    scale=[10, 10]
)

In [22]:
output = gaussian_model(x_dummy)

In [23]:
# Print input and output
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 90., 180.],
        [-90., 180.],
        [ 90., 180.],
        [  0., 180.]])
Output:
tensor([[-2.4421, -0.7985],
        [ 1.3590,  0.6936],
        [ 0.6545,  2.1849],
        [-1.9516, -2.0635]], grad_fn=<MmBackward0>)


In [24]:
model_summary(gaussian_model, input_size=(1, 2))

Layer (type:depth-idx)                        Output Shape              Param #
GaussianModel                                 [1, 2]                    --
├─SphericalFourierFeatureTransform: 1-1       [1, 440]                  --
├─Sequential: 1-2                             [1, 2]                    --
│    └─GaussianLayer: 2-1                     [1, 512]                  --
│    │    └─Linear: 3-1                       [1, 512]                  225,792
│    │    └─gaussian_activation: 3-2          [1, 512]                  --
│    │    └─Identity: 3-3                     [1, 512]                  --
│    └─GaussianLayer: 2-2                     [1, 512]                  --
│    │    └─Linear: 3-4                       [1, 512]                  262,656
│    │    └─gaussian_activation: 3-5          [1, 512]                  --
│    │    └─Dropout: 3-6                      [1, 512]                  --
│    └─GaussianLayer: 2-3                     [1, 512]                  --
│    │    

In [25]:
gaussian_residual_model = GaussianModel(
    in_features=2,
    out_features=2,
    hidden_layers=5,
    hidden_features=512,
    scale_gaussian=30.0,
    weight_init=0.1,
    dropout=0.1,
    residual_net=True,
    encoding='dfs',
    r_min=0.001,
    r_max=1.0,
    scale=[10, 10]
)

In [26]:
output = gaussian_residual_model(x_dummy)

In [27]:
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 90., 180.],
        [-90., 180.],
        [ 90., 180.],
        [  0., 180.]])
Output:
tensor([[ 0.0290, -0.5388],
        [ 0.0094, -0.0884],
        [ 0.0419,  0.0247],
        [ 0.1025, -0.1655]], grad_fn=<MmBackward0>)


In [28]:
model_summary(gaussian_residual_model, input_size=(1, 2))

Layer (type:depth-idx)                        Output Shape              Param #
GaussianModel                                 [1, 2]                    --
├─SphericalFourierFeatureTransform: 1-1       [1, 440]                  --
├─Sequential: 1-2                             [1, 2]                    --
│    └─GaussianLayer: 2-1                     [1, 512]                  --
│    │    └─Linear: 3-1                       [1, 512]                  225,792
│    │    └─gaussian_activation: 3-2          [1, 512]                  --
│    │    └─Identity: 3-3                     [1, 512]                  --
│    └─GaussianResidualLayer: 2-2             [1, 512]                  --
│    │    └─Linear: 3-4                       [1, 512]                  262,656
│    │    └─gaussian_activation: 3-5          [1, 512]                  --
│    │    └─Linear: 3-6                       [1, 512]                  262,656
│    │    └─gaussian_activation: 3-7          [1, 512]                  --
│    

In [29]:
gaussian_finer_model = GaussianFinerModel(
    in_features=2,
    out_features=2,
    scale_gaussian=20.0,
    omega_f=1,
    first_k=30,
    hidden_k=30,
    dropout=0.1,
    residual_net=False,
    encoding='dfs',
    r_min=0.001,
    r_max=1.0,
    scale=[10, 10]
)

In [30]:
output = gaussian_finer_model(x_dummy)

In [31]:
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 90., 180.],
        [-90., 180.],
        [ 90., 180.],
        [  0., 180.]])
Output:
tensor([[ 0.2929, -0.0189],
        [ 0.1909,  0.0904],
        [-0.0579,  0.4307],
        [ 0.0356,  0.1008]], grad_fn=<MmBackward0>)


In [32]:
model_summary(gaussian_finer_model, input_size=(1, 2))

Layer (type:depth-idx)                        Output Shape              Param #
GaussianFinerModel                            [1, 2]                    --
├─SphericalFourierFeatureTransform: 1-1       [1, 440]                  --
├─Sequential: 1-2                             [1, 2]                    --
│    └─GaussianFinerLayer: 2-1                [1, 128]                  --
│    │    └─Linear: 3-1                       [1, 128]                  56,448
│    │    └─gaussian_activation: 3-2          [1, 128]                  --
│    │    └─Identity: 3-3                     [1, 128]                  --
│    └─GaussianFinerLayer: 2-2                [1, 128]                  --
│    │    └─Linear: 3-4                       [1, 128]                  16,512
│    │    └─gaussian_activation: 3-5          [1, 128]                  --
│    │    └─Dropout: 3-6                      [1, 128]                  --
│    └─GaussianFinerLayer: 2-3                [1, 128]                  --
│    │    └─

In [33]:
gaussian_finer_residual_model = GaussianFinerModel(
    in_features=2,
    out_features=2,
    scale_gaussian=30.0,
    omega_f=2.5,
    first_k=1,
    hidden_k=1,
    dropout=0.1,
    residual_net=True,
    encoding='dfs',
    r_min=0.001,
    r_max=1.0,
    scale=[10, 10]
)

In [34]:
output = gaussian_finer_residual_model(x_dummy)

In [35]:
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 90., 180.],
        [-90., 180.],
        [ 90., 180.],
        [  0., 180.]])
Output:
tensor([[-0.0482,  0.0326],
        [ 0.0446,  0.1635],
        [ 0.0327,  0.0728],
        [-0.1105,  0.0579]], grad_fn=<MmBackward0>)


In [36]:
model_summary(gaussian_finer_residual_model, input_size=(1, 2))

Layer (type:depth-idx)                        Output Shape              Param #
GaussianFinerModel                            [1, 2]                    --
├─SphericalFourierFeatureTransform: 1-1       [1, 440]                  --
├─Sequential: 1-2                             [1, 2]                    --
│    └─GaussianFinerLayer: 2-1                [1, 128]                  --
│    │    └─Linear: 3-1                       [1, 128]                  56,448
│    │    └─gaussian_activation: 3-2          [1, 128]                  --
│    │    └─Identity: 3-3                     [1, 128]                  --
│    └─GaussianFinerResidualLayer: 2-2        [1, 128]                  --
│    │    └─Linear: 3-4                       [1, 128]                  16,512
│    │    └─gaussian_activation: 3-5          [1, 128]                  --
│    │    └─Linear: 3-6                       [1, 128]                  16,512
│    │    └─gaussian_activation: 3-7          [1, 128]                  --
│    │  

## MLP MODEL

In [37]:
from models.implicit_neural_representations.inr_models.mlp_model import MLPModel

In [38]:
mlp_model = MLPModel(
    in_features=2,
    out_features=1,
    hidden_features=512,
    hidden_layers = 5, 
    bias=True,
    weight_init=0.1,
    bias_init=None,
    dropout=0.1,
    residual_net=False,
    encoding='dfs',
    r_min=0.001,
    r_max = 1.0,
    scale = [2, 2])

In [39]:
output = mlp_model(x_dummy)

In [40]:
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 90., 180.],
        [-90., 180.],
        [ 90., 180.],
        [  0., 180.]])
Output:
tensor([[-0.1027],
        [ 0.0922],
        [-0.2706],
        [ 0.0737]], grad_fn=<AddmmBackward0>)


In [41]:
model_summary(mlp_model, input_size=(1, 2))

Layer (type:depth-idx)                        Output Shape              Param #
MLPModel                                      [1, 1]                    --
├─SphericalFourierFeatureTransform: 1-1       [1, 24]                   --
├─Sequential: 1-2                             [1, 1]                    --
│    └─MLPLayer: 2-1                          [1, 512]                  --
│    │    └─Linear: 3-1                       [1, 512]                  12,800
│    │    └─Identity: 3-2                     [1, 512]                  --
│    │    └─ReLU: 3-3                         [1, 512]                  --
│    └─MLPLayer: 2-2                          [1, 512]                  --
│    │    └─Linear: 3-4                       [1, 512]                  262,656
│    │    └─Dropout: 3-5                      [1, 512]                  --
│    │    └─ReLU: 3-6                         [1, 512]                  --
│    └─MLPLayer: 2-3                          [1, 512]                  --
│    │    └

In [42]:
mlp_residual_model = MLPModel(
    in_features=2,
    out_features=2,
    hidden_features=128,
    hidden_layers = 5, 
    bias=True,
    weight_init=0.1,
    bias_init=None,
    dropout=0.1,
    residual_net=True,
    encoding='dfs',
    r_min=0.001,
    r_max = 1.0,
    scale = [10, 10]
)

In [43]:
output = mlp_residual_model(x_dummy)

In [44]:
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 90., 180.],
        [-90., 180.],
        [ 90., 180.],
        [  0., 180.]])
Output:
tensor([[-0.6904, -0.0634],
        [-0.3480,  0.3361],
        [-0.7009,  0.1384],
        [-0.2837,  0.2321]], grad_fn=<AddmmBackward0>)


In [45]:
model_summary(mlp_residual_model, input_size=(1, 2))

Layer (type:depth-idx)                        Output Shape              Param #
MLPModel                                      [1, 2]                    --
├─SphericalFourierFeatureTransform: 1-1       [1, 440]                  --
├─Sequential: 1-2                             [1, 2]                    --
│    └─MLPLayer: 2-1                          [1, 128]                  --
│    │    └─Linear: 3-1                       [1, 128]                  56,448
│    │    └─Identity: 3-2                     [1, 128]                  --
│    │    └─ReLU: 3-3                         [1, 128]                  --
│    └─MLPResidualLayer: 2-2                  [1, 128]                  --
│    │    └─Linear: 3-4                       [1, 128]                  16,512
│    │    └─ReLU: 3-5                         [1, 128]                  --
│    │    └─Linear: 3-6                       [1, 128]                  16,512
│    │    └─Dropout: 3-7                      [1, 128]                  --
│    │  

## Wire Models

In [46]:
from models.implicit_neural_representations.inr_models.wire_model import WireModel, WireFinerModel

In [47]:
wire_model = WireModel(
    in_features=2,
    out_features=2,
    hidden_features=128,
    hidden_layers = 5, 
    scale_wire=10.0,
    omega=20.0,
    bias=True,
    weight_init=0.1,
    bias_init=None,
    dropout=0.0,
    residual_net=False,
    encoding='dfs',
    r_min=0.001,
    r_max=1.0,
    scale=[10, 10]
)

In [48]:
output = wire_model(x_dummy)

In [49]:
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 90., 180.],
        [-90., 180.],
        [ 90., 180.],
        [  0., 180.]])
Output:
tensor([[-0.2503+0.2237j,  0.2870-0.1202j],
        [ 0.4933-0.0632j, -0.3285-0.2422j],
        [-0.2503+0.2237j,  0.2870-0.1202j],
        [-0.8148-0.1963j, -0.7929+0.4870j]], grad_fn=<MmBackward0>)


In [50]:
model_summary(wire_model, input_size=(1, 2))

Layer (type:depth-idx)                        Output Shape              Param #
WireModel                                     [1, 2]                    --
├─SphericalFourierFeatureTransform: 1-1       [1, 440]                  --
├─Sequential: 1-2                             [1, 2]                    --
│    └─WireLayer: 2-1                         [1, 128]                  --
│    │    └─Linear: 3-1                       [1, 128]                  56,448
│    │    └─wire_activation: 3-2              [1, 128]                  --
│    │    └─Identity: 3-3                     [1, 128]                  --
│    └─WireLayer: 2-2                         [1, 128]                  --
│    │    └─Linear: 3-4                       [1, 128]                  16,512
│    │    └─wire_activation: 3-5              [1, 128]                  --
│    │    └─Identity: 3-6                     [1, 128]                  --
│    └─WireLayer: 2-3                         [1, 128]                  --
│    │    └─

In [51]:
wire_residual_model = WireModel(
    in_features=2,
    out_features=2,
    hidden_features=128,
    hidden_layers = 5,
    scale_wire=10.0,
    omega=20.0,
    bias=True,
    weight_init=0.1,
    bias_init=None,
    dropout=0.0,
    residual_net=True,
    encoding='dfs',
    r_min=0.001,
    r_max=1.0,
    scale=[10, 10]
)

In [52]:
output = wire_residual_model(x_dummy)

In [53]:
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 90., 180.],
        [-90., 180.],
        [ 90., 180.],
        [  0., 180.]])
Output:
tensor([[0.0035+0.2175j, 0.0181+0.0312j],
        [0.0280+0.0518j, 0.0886+0.3949j],
        [0.0035+0.2175j, 0.0181+0.0312j],
        [0.4289-0.6422j, 0.9863+0.1847j]], grad_fn=<MmBackward0>)


In [54]:
model_summary(wire_residual_model, input_size=(1, 2))

Layer (type:depth-idx)                        Output Shape              Param #
WireModel                                     [1, 2]                    --
├─SphericalFourierFeatureTransform: 1-1       [1, 440]                  --
├─Sequential: 1-2                             [1, 2]                    --
│    └─WireLayer: 2-1                         [1, 128]                  --
│    │    └─Linear: 3-1                       [1, 128]                  56,448
│    │    └─wire_activation: 3-2              [1, 128]                  --
│    │    └─Identity: 3-3                     [1, 128]                  --
│    └─WireResidualLayer: 2-2                 [1, 128]                  --
│    │    └─Linear: 3-4                       [1, 128]                  16,512
│    │    └─wire_activation: 3-5              [1, 128]                  --
│    │    └─Linear: 3-6                       [1, 128]                  16,512
│    │    └─wire_activation: 3-7              [1, 128]                  --
│    │  

In [55]:
torch.abs(x_dummy - output)

tensor([[ 89.9967, 179.9819],
        [ 90.0281, 179.9118],
        [ 89.9967, 179.9819],
        [  0.7723, 179.0138]], grad_fn=<AbsBackward0>)

In [56]:
x_dummy - output

tensor([[ 89.9965-0.2175j, 179.9819-0.0312j],
        [-90.0280-0.0518j, 179.9114-0.3949j],
        [ 89.9965-0.2175j, 179.9819-0.0312j],
        [ -0.4289+0.6422j, 179.0137-0.1847j]], grad_fn=<SubBackward0>)

In [57]:
torch.abs(output) 

tensor([[0.2175, 0.0360],
        [0.0589, 0.4047],
        [0.2175, 0.0360],
        [0.7723, 1.0034]], grad_fn=<AbsBackward0>)

In [58]:
wire_finer_model = WireFinerModel(
    in_features=2,
    out_features=2,
    hidden_features=512,
    hidden_layers = 5, 
    scale_wire=10.0,
    omega=20.0,
    omega_f=1.0,
    bias=True,
    first_k=5,
    hidden_k=5,
    dropout=0.0,
    residual_net=False,
    encoding='dfs',
    r_min=0.001,
    r_max=1.0,
    scale=[10, 10]
)

In [59]:
output = wire_finer_model(x_dummy)

In [60]:
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 90., 180.],
        [-90., 180.],
        [ 90., 180.],
        [  0., 180.]])
Output:
tensor([[ 0.0107-0.2083j,  0.1867-0.0736j],
        [ 0.0529-0.1732j,  0.1812+0.1032j],
        [ 0.0107-0.2083j,  0.1867-0.0736j],
        [-0.0201-0.2010j,  0.1699-0.1079j]], grad_fn=<MmBackward0>)


In [61]:
model_summary(wire_finer_model, input_size=(1, 2))

Layer (type:depth-idx)                        Output Shape              Param #
WireFinerModel                                [1, 2]                    --
├─SphericalFourierFeatureTransform: 1-1       [1, 440]                  --
├─Sequential: 1-2                             [1, 2]                    --
│    └─WireFinerLayer: 2-1                    [1, 512]                  --
│    │    └─Linear: 3-1                       [1, 512]                  225,792
│    │    └─wire_activation: 3-2              [1, 512]                  --
│    │    └─Identity: 3-3                     [1, 512]                  --
│    └─WireFinerLayer: 2-2                    [1, 512]                  --
│    │    └─Linear: 3-4                       [1, 512]                  262,656
│    │    └─wire_activation: 3-5              [1, 512]                  --
│    │    └─Identity: 3-6                     [1, 512]                  --
│    └─WireFinerLayer: 2-3                    [1, 512]                  --
│    │    

In [62]:
wire_finer_residual_model = WireFinerModel(
    in_features=2,
    out_features=2,
    hidden_features=1024,
    hidden_layers = 1, 
    scale_wire=10.0,
    omega=20.0,
    omega_f=2.5,
    bias=True,
    first_k=2,
    hidden_k=2,
    dropout=0.0,
    residual_net=True,
    encoding='sphere2vec',
    r_min=0.001,
    r_max=1.0,
    scale=10,
    mode='SphereC'
)

In [63]:
output = wire_finer_residual_model(x_dummy)

In [64]:
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 90., 180.],
        [-90., 180.],
        [ 90., 180.],
        [  0., 180.]])
Output:
tensor([[ 0.0063+0.0749j, -0.0970+0.0597j],
        [-0.0145-0.0696j,  0.0441-0.0514j],
        [ 0.0063+0.0749j, -0.0970+0.0597j],
        [ 0.0455-0.1178j, -0.1240+0.0394j]], grad_fn=<MmBackward0>)


In [65]:
model_summary(wire_finer_residual_model, input_size=(1, 2))

Layer (type:depth-idx)                   Output Shape              Param #
WireFinerModel                           [1, 2]                    --
├─Sphere2Vec: 1-1                        [1, 30]                   --
├─Sequential: 1-2                        [1, 2]                    --
│    └─WireFinerLayer: 2-1               [1, 1024]                 --
│    │    └─Linear: 3-1                  [1, 1024]                 31,744
│    │    └─wire_activation: 3-2         [1, 1024]                 --
│    │    └─Identity: 3-3                [1, 1024]                 --
│    └─WireFinerResidualLayer: 2-2       [1, 1024]                 --
│    │    └─Linear: 3-4                  [1, 1024]                 1,049,600
│    │    └─wire_activation: 3-5         [1, 1024]                 --
│    │    └─Linear: 3-6                  [1, 1024]                 1,049,600
│    │    └─wire_activation: 3-7         [1, 1024]                 --
│    │    └─Identity: 3-8                [1, 1024]                 