In [1]:
import torch
from helpers import model_summary
x_dummy = torch.tensor([[90.0, 180.0],
                        [-90.0,180.0],
                        [90.0,180.0],
                        [0.0, 180.0]])

In [2]:
print(x_dummy)

tensor([[ 90., 180.],
        [-90., 180.],
        [ 90., 180.],
        [  0., 180.]])


## SIREN and FINER MODEL

In [3]:
from models.implicit_neural_representations.inr_models.siren_model import SirenModel, FinerModel

In [4]:
# initialize siren model without residual layers
siren_model = SirenModel(
    in_features=2,
    out_features=2,
    hidden_layers=5,
    hidden_features=512,
    first_omega_0=30.0,
    hidden_omega_0=30.0,
    residual_net=False,
    encoding='dfs',
    r_min=0.001,
    r_max=1.0,
    scale=[10, 10]
)

In [5]:
output = siren_model(x_dummy)

In [6]:
# Print input and output
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 90., 180.],
        [-90., 180.],
        [ 90., 180.],
        [  0., 180.]])
Output:
tensor([[ 0.0057,  0.0046],
        [-0.0045, -0.0196],
        [ 0.0057,  0.0046],
        [ 0.0341,  0.0101]], grad_fn=<MmBackward0>)


In [7]:
model_summary(siren_model, input_size=(1, 2))

Layer (type:depth-idx)                        Output Shape              Param #
SirenModel                                    [1, 2]                    --
├─SphericalFourierFeatureTransform: 1-1       [1, 440]                  --
├─Sequential: 1-2                             [1, 2]                    --
│    └─SirenLayer: 2-1                        [1, 512]                  --
│    │    └─Linear: 3-1                       [1, 512]                  225,792
│    │    └─siren_activation: 3-2             [1, 512]                  --
│    └─SirenLayer: 2-2                        [1, 512]                  --
│    │    └─Linear: 3-3                       [1, 512]                  262,656
│    │    └─siren_activation: 3-4             [1, 512]                  --
│    └─SirenLayer: 2-3                        [1, 512]                  --
│    │    └─Linear: 3-5                       [1, 512]                  262,656
│    │    └─siren_activation: 3-6             [1, 512]                  --
│    

In [8]:
finer_model = FinerModel(
    in_features=2,
    out_features=2,
    bias=True,
    hidden_layers=5,
    hidden_features=128,
    first_omega_0=30.,
    hidden_omega_0=30.,
    first_k=10,
    hidden_k=10,
    residual_net=False,
    encoding='dfs',
    r_min=0.001,
    r_max=1.0,
    scale=[10, 10]
)

In [9]:
output = finer_model(x_dummy)

In [10]:
# Print input and output
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 90., 180.],
        [-90., 180.],
        [ 90., 180.],
        [  0., 180.]])
Output:
tensor([[ 0.0340,  0.0382],
        [ 0.0046, -0.0257],
        [ 0.0340,  0.0382],
        [-0.0686,  0.0460]], grad_fn=<MmBackward0>)


In [11]:
model_summary(finer_model, input_size=(1, 2))

Layer (type:depth-idx)                        Output Shape              Param #
FinerModel                                    [1, 2]                    --
├─SphericalFourierFeatureTransform: 1-1       [1, 440]                  --
├─Sequential: 1-2                             [1, 2]                    --
│    └─FinerLayer: 2-1                        [1, 128]                  --
│    │    └─Linear: 3-1                       [1, 128]                  56,448
│    │    └─siren_activation: 3-2             [1, 128]                  --
│    └─FinerLayer: 2-2                        [1, 128]                  --
│    │    └─Linear: 3-3                       [1, 128]                  16,512
│    │    └─siren_activation: 3-4             [1, 128]                  --
│    └─FinerLayer: 2-3                        [1, 128]                  --
│    │    └─Linear: 3-5                       [1, 128]                  16,512
│    │    └─siren_activation: 3-6             [1, 128]                  --
│    └─F

In [12]:
siren_residual_model = SirenModel(
    in_features=2,
    out_features=2,
    hidden_layers=5,
    hidden_features=512,
    first_omega_0=30.0,
    hidden_omega_0=30.0,
    residual_net=True,
    encoding='dfs',
    r_min=0.001,
    r_max=1.0,
    scale=[10, 10]
)

In [13]:
output = siren_residual_model(x_dummy)

In [14]:
# Print input and output
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 90., 180.],
        [-90., 180.],
        [ 90., 180.],
        [  0., 180.]])
Output:
tensor([[ 0.0008, -0.0024],
        [-0.0307, -0.0163],
        [ 0.0008, -0.0024],
        [ 0.0157,  0.0221]], grad_fn=<MmBackward0>)


In [15]:
model_summary(siren_residual_model, input_size=(1, 2))

Layer (type:depth-idx)                        Output Shape              Param #
SirenModel                                    [1, 2]                    --
├─SphericalFourierFeatureTransform: 1-1       [1, 440]                  --
├─Sequential: 1-2                             [1, 2]                    --
│    └─SirenLayer: 2-1                        [1, 512]                  --
│    │    └─Linear: 3-1                       [1, 512]                  225,792
│    │    └─siren_activation: 3-2             [1, 512]                  --
│    └─SirenResidualLayer: 2-2                [1, 512]                  --
│    │    └─Linear: 3-3                       [1, 512]                  262,656
│    │    └─siren_activation: 3-4             [1, 512]                  --
│    │    └─Linear: 3-5                       [1, 512]                  262,656
│    │    └─siren_activation: 3-6             [1, 512]                  --
│    └─SirenResidualLayer: 2-3                [1, 512]                  --
│    

In [16]:
finer_residual_model = FinerModel( 
    in_features=2,
    out_features=2,
    bias=True,
    hidden_layers=5,
    hidden_features=128,
    first_omega_0=30.,
    hidden_omega_0=30.,
    first_k=10,
    hidden_k=10,
    residual_net=True,
    encoding='dfs',
    r_min=0.001,
    r_max=1.0,
    scale=[10, 10]
)

In [17]:
output = finer_residual_model(x_dummy)

In [18]:
# Print input and output
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 90., 180.],
        [-90., 180.],
        [ 90., 180.],
        [  0., 180.]])
Output:
tensor([[ 0.0817,  0.0108],
        [ 0.0112,  0.0693],
        [ 0.0817,  0.0108],
        [-0.0186, -0.0273]], grad_fn=<MmBackward0>)


In [19]:
model_summary(finer_residual_model, input_size=(1, 2))

Layer (type:depth-idx)                        Output Shape              Param #
FinerModel                                    [1, 2]                    --
├─SphericalFourierFeatureTransform: 1-1       [1, 440]                  --
├─Sequential: 1-2                             [1, 2]                    --
│    └─FinerLayer: 2-1                        [1, 128]                  --
│    │    └─Linear: 3-1                       [1, 128]                  56,448
│    │    └─siren_activation: 3-2             [1, 128]                  --
│    └─FinerResidualLayer: 2-2                [1, 128]                  --
│    │    └─Linear: 3-3                       [1, 128]                  16,512
│    │    └─siren_activation: 3-4             [1, 128]                  --
│    │    └─Linear: 3-5                       [1, 128]                  16,512
│    │    └─siren_activation: 3-6             [1, 128]                  --
│    └─FinerResidualLayer: 2-3                [1, 128]                  --
│    │  

## Gaussian Model and Finer Gaussian

In [20]:
from models.implicit_neural_representations.inr_models.gaussian_model import GaussianModel, GaussianFinerModel

In [21]:
# initialize gaussian model without residual layers
gaussian_model = GaussianModel(
    in_features=2,
    out_features=2,
    hidden_layers=5,
    hidden_features=512,
    scale_gaussian=30.0,
    weight_init=2.0,
    bias_init=2.0,
    residual_net=False,
    encoding='dfs',
    r_min=0.001,
    r_max=1.0,
    scale=[10, 10]
)

In [22]:
output = gaussian_model(x_dummy)

In [23]:
# Print input and output
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 90., 180.],
        [-90., 180.],
        [ 90., 180.],
        [  0., 180.]])
Output:
tensor([[ 1.0721,  0.7641],
        [ 0.5402, -1.9256],
        [ 1.0721,  0.7641],
        [ 0.5134,  2.0440]], grad_fn=<MmBackward0>)


In [24]:
model_summary(gaussian_model, input_size=(1, 2))

Layer (type:depth-idx)                        Output Shape              Param #
GaussianModel                                 [1, 2]                    --
├─SphericalFourierFeatureTransform: 1-1       [1, 440]                  --
├─Sequential: 1-2                             [1, 2]                    --
│    └─GaussianLayer: 2-1                     [1, 512]                  --
│    │    └─Linear: 3-1                       [1, 512]                  225,792
│    │    └─gaussian_activation: 3-2          [1, 512]                  --
│    └─GaussianLayer: 2-2                     [1, 512]                  --
│    │    └─Linear: 3-3                       [1, 512]                  262,656
│    │    └─gaussian_activation: 3-4          [1, 512]                  --
│    └─GaussianLayer: 2-3                     [1, 512]                  --
│    │    └─Linear: 3-5                       [1, 512]                  262,656
│    │    └─gaussian_activation: 3-6          [1, 512]                  --
│    

In [25]:
gaussian_residual_model = GaussianModel(
    in_features=2,
    out_features=2,
    hidden_layers=5,
    hidden_features=512,
    scale_gaussian=30.0,
    weight_init=0.1,
    residual_net=True,
    encoding='dfs',
    r_min=0.001,
    r_max=1.0,
    scale=[10, 10]
)

In [26]:
output = gaussian_residual_model(x_dummy)

In [27]:
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 90., 180.],
        [-90., 180.],
        [ 90., 180.],
        [  0., 180.]])
Output:
tensor([[-0.3675,  0.4428],
        [ 0.1849,  0.2407],
        [-0.3675,  0.4428],
        [ 0.0943,  0.0681]], grad_fn=<MmBackward0>)


In [28]:
model_summary(gaussian_residual_model, input_size=(1, 2))

Layer (type:depth-idx)                        Output Shape              Param #
GaussianModel                                 [1, 2]                    --
├─SphericalFourierFeatureTransform: 1-1       [1, 440]                  --
├─Sequential: 1-2                             [1, 2]                    --
│    └─GaussianLayer: 2-1                     [1, 512]                  --
│    │    └─Linear: 3-1                       [1, 512]                  225,792
│    │    └─gaussian_activation: 3-2          [1, 512]                  --
│    └─GaussianResidualLayer: 2-2             [1, 512]                  --
│    │    └─Linear: 3-3                       [1, 512]                  262,656
│    │    └─gaussian_activation: 3-4          [1, 512]                  --
│    │    └─Linear: 3-5                       [1, 512]                  262,656
│    │    └─gaussian_activation: 3-6          [1, 512]                  --
│    └─GaussianResidualLayer: 2-3             [1, 512]                  --
│    

In [29]:
gaussian_finer_model = GaussianFinerModel(
    in_features=2,
    out_features=2,
    scale_gaussian=20.0,
    omega_f=1,
    first_k=30,
    hidden_k=30,
    residual_net=False,
    encoding='dfs',
    r_min=0.001,
    r_max=1.0,
    scale=[10, 10]
)

In [30]:
output = gaussian_finer_model(x_dummy)

In [31]:
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 90., 180.],
        [-90., 180.],
        [ 90., 180.],
        [  0., 180.]])
Output:
tensor([[ 0.0366, -0.1536],
        [ 0.0709, -0.0311],
        [ 0.0366, -0.1536],
        [-0.0878, -0.1235]], grad_fn=<MmBackward0>)


In [32]:
model_summary(gaussian_finer_model, input_size=(1, 2))

Layer (type:depth-idx)                        Output Shape              Param #
GaussianFinerModel                            [1, 2]                    --
├─SphericalFourierFeatureTransform: 1-1       [1, 440]                  --
├─Sequential: 1-2                             [1, 2]                    --
│    └─GaussianFinerLayer: 2-1                [1, 128]                  --
│    │    └─Linear: 3-1                       [1, 128]                  56,448
│    │    └─gaussian_activation: 3-2          [1, 128]                  --
│    └─GaussianFinerLayer: 2-2                [1, 128]                  --
│    │    └─Linear: 3-3                       [1, 128]                  16,512
│    │    └─gaussian_activation: 3-4          [1, 128]                  --
│    └─GaussianFinerLayer: 2-3                [1, 128]                  --
│    │    └─Linear: 3-5                       [1, 128]                  16,512
│    │    └─gaussian_activation: 3-6          [1, 128]                  --
│    └─G

In [33]:
gaussian_finer_residual_model = GaussianFinerModel(
    in_features=2,
    out_features=2,
    scale_gaussian=30.0,
    omega_f=2.5,
    first_k=1,
    hidden_k=1,
    residual_net=True,
    encoding='dfs',
    r_min=0.001,
    r_max=1.0,
    scale=[10, 10]
)

In [34]:
output = gaussian_finer_residual_model(x_dummy)

In [35]:
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 90., 180.],
        [-90., 180.],
        [ 90., 180.],
        [  0., 180.]])
Output:
tensor([[ 0.1456, -0.0904],
        [-0.0259,  0.1640],
        [ 0.1456, -0.0904],
        [ 0.0645, -0.0679]], grad_fn=<MmBackward0>)


In [36]:
model_summary(gaussian_finer_residual_model, input_size=(1, 2))

Layer (type:depth-idx)                        Output Shape              Param #
GaussianFinerModel                            [1, 2]                    --
├─SphericalFourierFeatureTransform: 1-1       [1, 440]                  --
├─Sequential: 1-2                             [1, 2]                    --
│    └─GaussianFinerLayer: 2-1                [1, 128]                  --
│    │    └─Linear: 3-1                       [1, 128]                  56,448
│    │    └─gaussian_activation: 3-2          [1, 128]                  --
│    └─GaussianFinerResidualLayer: 2-2        [1, 128]                  --
│    │    └─Linear: 3-3                       [1, 128]                  16,512
│    │    └─gaussian_activation: 3-4          [1, 128]                  --
│    │    └─Linear: 3-5                       [1, 128]                  16,512
│    │    └─gaussian_activation: 3-6          [1, 128]                  --
│    └─GaussianFinerResidualLayer: 2-3        [1, 128]                  --
│    │  

## MLP MODEL

In [37]:
from models.implicit_neural_representations.inr_models.mlp_model import MLPModel

In [38]:
mlp_model = MLPModel(
    in_features=2,
    out_features=1,
    hidden_features=512,
    hidden_layers = 5, 
    bias=True,
    weight_init=0.1,
    bias_init=None,
    residual_net=False,
    encoding='dfs',
    r_min=0.001,
    r_max = 1.0,
    scale = [2, 2])

In [39]:
output = mlp_model(x_dummy)

In [40]:
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 90., 180.],
        [-90., 180.],
        [ 90., 180.],
        [  0., 180.]])
Output:
tensor([[-0.0041],
        [-0.0251],
        [-0.0041],
        [ 0.0465]], grad_fn=<AddmmBackward0>)


In [41]:
model_summary(mlp_model, input_size=(1, 2))

Layer (type:depth-idx)                        Output Shape              Param #
MLPModel                                      [1, 1]                    --
├─SphericalFourierFeatureTransform: 1-1       [1, 24]                   --
├─Sequential: 1-2                             [1, 1]                    --
│    └─MLPLayer: 2-1                          [1, 512]                  --
│    │    └─Linear: 3-1                       [1, 512]                  12,800
│    │    └─ReLU: 3-2                         [1, 512]                  --
│    └─MLPLayer: 2-2                          [1, 512]                  --
│    │    └─Linear: 3-3                       [1, 512]                  262,656
│    │    └─ReLU: 3-4                         [1, 512]                  --
│    └─MLPLayer: 2-3                          [1, 512]                  --
│    │    └─Linear: 3-5                       [1, 512]                  262,656
│    │    └─ReLU: 3-6                         [1, 512]                  --
│    └

In [42]:
mlp_residual_model = MLPModel(
    in_features=2,
    out_features=2,
    hidden_features=128,
    hidden_layers = 5, 
    bias=True,
    weight_init=0.1,
    bias_init=None,
    residual_net=True,
    encoding='dfs',
    r_min=0.001,
    r_max = 1.0,
    scale = [10, 10]
)

In [43]:
output = mlp_residual_model(x_dummy)

In [44]:
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 90., 180.],
        [-90., 180.],
        [ 90., 180.],
        [  0., 180.]])
Output:
tensor([[-0.4899,  0.5140],
        [-0.2387,  0.1216],
        [-0.4899,  0.5140],
        [-0.1947,  0.1944]], grad_fn=<AddmmBackward0>)


In [45]:
model_summary(mlp_residual_model, input_size=(1, 2))

Layer (type:depth-idx)                        Output Shape              Param #
MLPModel                                      [1, 2]                    --
├─SphericalFourierFeatureTransform: 1-1       [1, 440]                  --
├─Sequential: 1-2                             [1, 2]                    --
│    └─MLPLayer: 2-1                          [1, 128]                  --
│    │    └─Linear: 3-1                       [1, 128]                  56,448
│    │    └─ReLU: 3-2                         [1, 128]                  --
│    └─MLPResidualLayer: 2-2                  [1, 128]                  --
│    │    └─Linear: 3-3                       [1, 128]                  16,512
│    │    └─ReLU: 3-4                         [1, 128]                  --
│    │    └─Linear: 3-5                       [1, 128]                  16,512
│    │    └─ReLU: 3-6                         [1, 128]                  --
│    └─MLPResidualLayer: 2-3                  [1, 128]                  --
│    │  

## Wire Models

In [46]:
from models.implicit_neural_representations.inr_models.wire_model import WireModel, WireFinerModel

In [47]:
wire_model = WireModel(
    in_features=2,
    out_features=2,
    hidden_features=128,
    hidden_layers = 5, 
    scale_wire=10.0,
    omega=20.0,
    bias=True,
    weight_init=0.1,
    bias_init=None,
    residual_net=False,
    encoding='dfs',
    r_min=0.001,
    r_max=1.0,
    scale=[10, 10]
)

In [48]:
output = wire_model(x_dummy)

In [49]:
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 90., 180.],
        [-90., 180.],
        [ 90., 180.],
        [  0., 180.]])
Output:
tensor([[ 0.1947+0.0195j, -0.2029+0.1827j],
        [ 0.2545-0.0731j, -0.1139-0.5072j],
        [ 0.1947+0.0195j, -0.2029+0.1827j],
        [ 0.1161+0.3340j,  0.0980+0.2947j]], grad_fn=<MmBackward0>)


In [50]:
model_summary(wire_model, input_size=(1, 2))

Layer (type:depth-idx)                        Output Shape              Param #
WireModel                                     [1, 2]                    --
├─SphericalFourierFeatureTransform: 1-1       [1, 440]                  --
├─Sequential: 1-2                             [1, 2]                    --
│    └─WireLayer: 2-1                         [1, 128]                  --
│    │    └─Linear: 3-1                       [1, 128]                  56,448
│    │    └─wire_activation: 3-2              [1, 128]                  --
│    └─WireLayer: 2-2                         [1, 128]                  --
│    │    └─Linear: 3-3                       [1, 128]                  16,512
│    │    └─wire_activation: 3-4              [1, 128]                  --
│    └─WireLayer: 2-3                         [1, 128]                  --
│    │    └─Linear: 3-5                       [1, 128]                  16,512
│    │    └─wire_activation: 3-6              [1, 128]                  --
│    └─W

In [51]:
wire_residual_model = WireModel(
    in_features=2,
    out_features=2,
    hidden_features=128,
    hidden_layers = 5,
    scale_wire=10.0,
    omega=20.0,
    bias=True,
    weight_init=0.1,
    bias_init=None,
    residual_net=True,
    encoding='dfs',
    r_min=0.001,
    r_max=1.0,
    scale=[10, 10]
)

In [52]:
output = wire_residual_model(x_dummy)

In [53]:
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 90., 180.],
        [-90., 180.],
        [ 90., 180.],
        [  0., 180.]])
Output:
tensor([[ 0.0714+0.0291j, -0.1542+0.5271j],
        [-0.0944+0.0199j,  0.0677-0.1978j],
        [ 0.0714+0.0291j, -0.1542+0.5271j],
        [ 0.1168-0.0809j,  0.0745-0.2087j]], grad_fn=<MmBackward0>)


In [54]:
model_summary(wire_residual_model, input_size=(1, 2))

Layer (type:depth-idx)                        Output Shape              Param #
WireModel                                     [1, 2]                    --
├─SphericalFourierFeatureTransform: 1-1       [1, 440]                  --
├─Sequential: 1-2                             [1, 2]                    --
│    └─WireLayer: 2-1                         [1, 128]                  --
│    │    └─Linear: 3-1                       [1, 128]                  56,448
│    │    └─wire_activation: 3-2              [1, 128]                  --
│    └─WireResidualLayer: 2-2                 [1, 128]                  --
│    │    └─Linear: 3-3                       [1, 128]                  16,512
│    │    └─wire_activation: 3-4              [1, 128]                  --
│    │    └─Linear: 3-5                       [1, 128]                  16,512
│    │    └─wire_activation: 3-6              [1, 128]                  --
│    └─WireResidualLayer: 2-3                 [1, 128]                  --
│    │  

In [55]:
torch.abs(x_dummy - output)

tensor([[8.9929e+01, 1.8015e+02],
        [8.9906e+01, 1.7993e+02],
        [8.9929e+01, 1.8015e+02],
        [1.4207e-01, 1.7993e+02]], grad_fn=<AbsBackward0>)

In [56]:
x_dummy - output

tensor([[ 8.9929e+01-0.0291j,  1.8015e+02-0.5271j],
        [-8.9906e+01-0.0199j,  1.7993e+02+0.1978j],
        [ 8.9929e+01-0.0291j,  1.8015e+02-0.5271j],
        [-1.1680e-01+0.0809j,  1.7993e+02+0.2087j]], grad_fn=<SubBackward0>)

In [57]:
torch.abs(output) 

tensor([[0.0771, 0.5492],
        [0.0965, 0.2090],
        [0.0771, 0.5492],
        [0.1421, 0.2216]], grad_fn=<AbsBackward0>)

In [58]:
wire_finer_model = WireFinerModel(
    in_features=2,
    out_features=2,
    hidden_features=512,
    hidden_layers = 5, 
    scale_wire=10.0,
    omega=20.0,
    omega_f=1.0,
    bias=True,
    first_k=5,
    hidden_k=5,
    residual_net=False,
    encoding='dfs',
    r_min=0.001,
    r_max=1.0,
    scale=[10, 10]
)

In [59]:
output = wire_finer_model(x_dummy)

In [60]:
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 90., 180.],
        [-90., 180.],
        [ 90., 180.],
        [  0., 180.]])
Output:
tensor([[-4.5587e-07-2.9958e-06j, -9.4984e-07-7.5627e-06j],
        [ 8.3030e-08+5.3224e-07j, -5.1123e-06-1.6288e-06j],
        [-4.5587e-07-2.9958e-06j, -9.4984e-07-7.5627e-06j],
        [-7.7997e-04+4.1095e-04j, -1.0881e-03+2.1391e-03j]],
       grad_fn=<MmBackward0>)


In [61]:
model_summary(wire_finer_model, input_size=(1, 2))

Layer (type:depth-idx)                        Output Shape              Param #
WireFinerModel                                [1, 2]                    --
├─SphericalFourierFeatureTransform: 1-1       [1, 440]                  --
├─Sequential: 1-2                             [1, 2]                    --
│    └─WireFinerLayer: 2-1                    [1, 512]                  --
│    │    └─Linear: 3-1                       [1, 512]                  225,792
│    │    └─wire_activation: 3-2              [1, 512]                  --
│    └─WireFinerLayer: 2-2                    [1, 512]                  --
│    │    └─Linear: 3-3                       [1, 512]                  262,656
│    │    └─wire_activation: 3-4              [1, 512]                  --
│    └─WireFinerLayer: 2-3                    [1, 512]                  --
│    │    └─Linear: 3-5                       [1, 512]                  262,656
│    │    └─wire_activation: 3-6              [1, 512]                  --
│    

In [69]:
wire_finer_residual_model = WireFinerModel(
    in_features=2,
    out_features=2,
    hidden_features=1024,
    hidden_layers = 1, 
    scale_wire=100.0,
    omega=100.0,
    omega_f=2.5,
    bias=True,
    first_k=2,
    hidden_k=2,
    residual_net=True,
    encoding='dfs',
    r_min=0.001,
    r_max=1.0,
    scale=[10, 10]
)

In [70]:
output = wire_finer_residual_model(x_dummy)

In [71]:
print("Input:")
print(x_dummy)
print("Output:")
print(output)

Input:
tensor([[ 90., 180.],
        [-90., 180.],
        [ 90., 180.],
        [  0., 180.]])
Output:
tensor([[1.7277e-07-1.6342e-07j, 1.9448e-07-9.8188e-08j],
        [3.0787e-07-2.5269e-07j, 3.3647e-07-1.4116e-07j],
        [1.7277e-07-1.6342e-07j, 1.9448e-07-9.8188e-08j],
        [1.7282e-07-1.6346e-07j, 1.9454e-07-9.8209e-08j]],
       grad_fn=<MmBackward0>)


In [65]:
model_summary(wire_finer_residual_model, input_size=(1, 2))

Layer (type:depth-idx)                        Output Shape              Param #
WireFinerModel                                [1, 2]                    --
├─SphericalFourierFeatureTransform: 1-1       [1, 440]                  --
├─Sequential: 1-2                             [1, 2]                    --
│    └─WireFinerLayer: 2-1                    [1, 128]                  --
│    │    └─Linear: 3-1                       [1, 128]                  56,448
│    │    └─wire_activation: 3-2              [1, 128]                  --
│    └─WireFinerResidualLayer: 2-2            [1, 128]                  --
│    │    └─Linear: 3-3                       [1, 128]                  16,512
│    │    └─wire_activation: 3-4              [1, 128]                  --
│    │    └─Linear: 3-5                       [1, 128]                  16,512
│    │    └─wire_activation: 3-6              [1, 128]                  --
│    └─Linear: 2-3                            [1, 2]                    256
Total p